using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Threading;

namespace FuelControl.Desktop.Services;

/// <summary>
/// Interfeys tili: uz (lotin), uzk (kirill), ru. XAML'da {l:T Kalit}, kodda Til.T("Kalit").
/// Til almashganda indekser bog'lanishlari ("Item[]") va Ozgardi hodisasi orqali hamma matn yangilanadi.
/// </summary>
public sealed class Til : INotifyPropertyChanged
{
    public static Til Joriy { get; } = new();
    public static event Action? Ozgardi;
    public event PropertyChangedEventHandler? PropertyChanged;

    public string Kod { get; private set; } = "uz";
    public bool Lotin => Kod == "uz";
    public bool Kirill => Kod == "uzk";
    public bool Ruscha => Kod == "ru";
    public string Qisqa => Kod switch { "uzk" => "ЎЗ", "ru" => "RU", _ => "UZ" };

    public string this[string kalit] => T(kalit);

    public static string T(string kalit)
    {
        if (!Lugat.TryGetValue(kalit, out var q)) return kalit;
        return Joriy.Kod switch { "uzk" => q.Kir, "ru" => q.Ru, _ => q.Lat };
    }

    /// <summary>Formatlash; "{n} L" va "{n} so'm" kabi birlik oldidagi bo'shliq bo'linmaydigan qilinadi.</summary>
    public static string F(string kalit, params object[] args) =>
        System.Text.RegularExpressions.Regex.Replace(string.Format(T(kalit), args), @"(\d) (L|Л|л|so'm|сўм|сум)\b", "$1\u00A0$2");

    public static bool Bormi(string kalit) => Lugat.ContainsKey(kalit);

    public void Tanla(string kod)
    {
        if (kod == Kod) return;
        Kod = kod;
        var c = (CultureInfo)CultureInfo.GetCultureInfo(kod switch { "uzk" => "uz-Cyrl-UZ", "ru" => "ru-RU", _ => "uz-Latn-UZ" }).Clone();
        c.NumberFormat.NumberDecimalSeparator = ".";
        c.NumberFormat.NumberGroupSeparator = " ";
        CultureInfo.DefaultThreadCurrentCulture = c;
        CultureInfo.DefaultThreadCurrentUICulture = c;
        Thread.CurrentThread.CurrentCulture = c;
        Thread.CurrentThread.CurrentUICulture = c;
        foreach (var n in new[] { nameof(Kod), nameof(Qisqa), nameof(Lotin), nameof(Kirill), nameof(Ruscha), "Item[]", string.Empty })
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(n));
        Ozgardi?.Invoke();
    }

    /// <summary>Keyingi tilga o'tish (yig'ilgan menyuda bitta tugma uchun).</summary>
    public void Keyingi() => Tanla(Kod switch { "uz" => "uzk", "uzk" => "ru", _ => "uz" });

    // Kalit → (lotin, kirill, ruscha)
    private static readonly Dictionary<string, (string Lat, string Kir, string Ru)> Lugat = new()
    {
        // ---- Umumiy / menyu
        ["BrendIzoh"] = ("Shoxobcha nazorati", "Шохобча назорати", "Контроль АЗС"),
        ["Boshqaruv"] = ("Boshqaruv", "Бошқарув", "Панель"),
        ["Smenalar"] = ("Smenalar", "Сменалар", "Смены"),
        ["Hisobotlar"] = ("Hisobotlar", "Ҳисоботлар", "Отчёты"),
        ["Operatorlar"] = ("Operatorlar", "Операторлар", "Операторы"),
        ["OperatorlarHisobi"] = ("Operatorlar hisobi", "Операторлар ҳисоби", "Счета операторов"),
        ["AuditJurnali"] = ("Audit jurnali", "Аудит журнали", "Журнал аудита"),
        ["Sozlamalar"] = ("Sozlamalar", "Созламалар", "Настройки"),
        ["MenyuniYig"] = ("Menyuni yig'ish", "Менюни йиғиш", "Свернуть меню"),
        ["MenyuniOch"] = ("Menyuni ochish", "Менюни очиш", "Развернуть меню"),
        ["QorongiRejim"] = ("Qorong'i rejim", "Қоронғи режим", "Тёмная тема"),
        ["RejimIzoh"] = ("Yorug' / qorong'i rejim", "Ёруғ / қоронғи режим", "Светлая / тёмная тема"),
        ["Chiqish"] = ("Chiqish", "Чиқиш", "Выйти"),
        ["ServerAloqa"] = ("Server bilan aloqa bor", "Сервер билан алоқа бор", "Связь с сервером есть"),
        ["ServerAloqaYoq"] = ("Aloqa yo'q", "Алоқа йўқ", "Нет связи"),
        ["Til"] = ("Til", "Тил", "Язык"),
        ["Som"] = ("so'm", "сўм", "сум"),
        ["L"] = ("l", "л", "л"),
        ["Soat"] = ("s", "с", "ч"),
        ["Jami"] = ("Jami", "Жами", "Итого"),
        ["Smena"] = ("Smena", "Смена", "Смена"),
        ["YoqilgiQoshish"] = ("Yoqilg'i qo'shish", "Ёқилғи қўшиш", "Добавить топливо"),
        ["YoqilginiTahrirlash"] = ("Yoqilg'ini tahrirlash", "Ёқилғини таҳрирлаш", "Изменить топливо"),
        ["YangiYoqilgi"] = ("Yangi yoqilg'i", "Янги ёқилғи", "Новое топливо"),
        ["Nomi"] = ("Nomi", "Номи", "Название"),
        ["Rang"] = ("Rang", "Ранг", "Цвет"),
        ["Ochirish"] = ("O'chirish", "Ўчириш", "Удалить"),
        ["Xato_YoqilgiBand"] = ("Bu nomli yoqilg'i allaqachon bor", "Бу номли ёқилғи аллақачон бор", "Топливо с таким названием уже есть"),
        ["Xato_YoqilgiIshlatilmoqda"] = ("Bu yoqilg'i aparatlarga biriktirilgan — avval aparatlarni o'zgartiring", "Бу ёқилғи апаратларга бириктирилган — аввал апаратларни ўзгартиринг", "Это топливо привязано к колонкам — сначала измените колонки"),
        ["NomiMisol"] = ("Masalan: AI-92, AI-95, Dizel, Metan", "Масалан: AI-92, AI-95, Дизел, Метан", "Например: АИ-92, АИ-95, Дизель, Метан"),
        ["BoshlangichQoldiq"] = ("Boshlang'ich qoldiq", "Бошланғич қолдиқ", "Начальный остаток"),
        ["YakuniyQoldiq"] = ("Yakuniy qoldiq", "Якуний қолдиқ", "Конечный остаток"),
        ["Tolovlar"] = ("To'lovlar", "Тўловлар", "Выплаты"),
        ["ExcelgaChiqarish"] = ("Excel (CSV) ga chiqarish", "Excel (CSV) га чиқариш", "Выгрузить в Excel (CSV)"),
        ["FaylSaqlandi"] = ("Fayl saqlandi", "Файл сақланди", "Файл сохранён"),
        ["Yopish"] = ("Yopish", "Ёпиш", "Закрыть"),
        ["OldingiOy"] = ("Oldingi oy", "Олдинги ой", "Предыдущий месяц"),
        ["KeyingiOy"] = ("Keyingi oy", "Кейинги ой", "Следующий месяц"),
        ["Jami_Kirim"] = ("Jami kirim", "Жами кирим", "Всего начислено"),
        ["Jami_Chiqim"] = ("Jami chiqim", "Жами чиқим", "Всего удержано"),
        ["YoqilgiTuri"] = ("Yoqilg'i turi", "Ёқилғи тури", "Вид топлива"),
        ["YangiAparat"] = ("Yangi aparat", "Янги апарат", "Новая колонка"),
        ["YangiFoydalanuvchi"] = ("Yangi foydalanuvchi", "Янги фойдаланувчи", "Новый пользователь"),
        ["FoydalanuvchiniTahrirlash"] = ("Foydalanuvchini tahrirlash", "Фойдаланувчини таҳрирлаш", "Изменить пользователя"),
        ["PinYokiParol"] = ("PIN / parol", "PIN / парол", "PIN / пароль"),
        ["YangiPinParol"] = ("Yangi PIN / parol", "Янги PIN / парол", "Новый PIN / пароль"),
        ["Tiklash"] = ("Tiklash", "Тиклаш", "Сбросить"),
        ["Nofaol"] = ("Nofaol", "Нофаол", "Отключён"),
        ["FaolHolat"] = ("Faol (tizimga kira oladi)", "Фаол (тизимга кира олади)", "Активен (может входить)"),
        ["Muvaffaqiyatli"] = ("muvaffaqiyatli", "муваффақиятли", "успешно"),
        ["Xato_Maydon"] = ("Barcha maydonlarni to'ldiring", "Барча майдонларни тўлдиринг", "Заполните все поля"),
        ["Xato_LoginBand"] = ("Bu login band", "Бу логин банд", "Этот логин занят"),
        ["ExcelPdf"] = ("Excel", "Excel", "Excel"),
        ["Vaqt"] = ("Vaqt", "Вақт", "Время"),
        ["Sana"] = ("Sana", "Сана", "Дата"),
        ["Oy"] = ("Oy", "Ой", "Месяц"),
        ["Operator"] = ("Operator", "Оператор", "Оператор"),
        ["Aparat"] = ("Aparat", "Aparat", "Колонка"),
        ["Yoqilgi"] = ("Yoqilg'i", "Ёқилғи", "Топливо"),
        ["Litr"] = ("Litr", "Литр", "Литры"),
        ["Summa"] = ("Summa", "Сумма", "Сумма"),
        ["Naqd"] = ("Naqd", "Нақд", "Наличные"),
        ["Plastik"] = ("Plastik", "Пластик", "Карта"),
        ["BekorQilish"] = ("Bekor qilish", "Бекор қилиш", "Отмена"),
        ["Saqlash"] = ("Saqlash", "Сақлаш", "Сохранить"),
        ["Tahrirlash"] = ("Tahrirlash", "Таҳрирлаш", "Изменить"),
        ["Izoh"] = ("Izoh", "Изоҳ", "Комментарий"),
        ["Kim"] = ("Kim", "Ким", "Кто"),

        // ---- Rollar
        ["Rol_Operator"] = ("Operator", "Оператор", "Оператор"),
        ["Rol_Boshliq"] = ("Boshliq", "Бошлиқ", "Руководитель"),
        ["Rol_Admin"] = ("Admin", "Админ", "Админ"),

        // ---- Kirish
        ["TizimgaKirish"] = ("Tizimga kirish", "Тизимга кириш", "Вход в систему"),
        ["KirishIzoh"] = ("Login va parol (operator — PIN) bilan", "Логин ва парол (оператор — PIN) билан", "Логин и пароль (оператор — PIN)"),
        ["Foydalanuvchi"] = ("Foydalanuvchi", "Фойдаланувчи", "Пользователь"),
        ["PinKod"] = ("PIN kod", "PIN код", "PIN-код"),
        ["Parol"] = ("Parol", "Парол", "Пароль"),
        ["ParolniKiriting"] = ("Parolni kiriting", "Паролни киритинг", "Введите пароль"),
        ["Kirish"] = ("Kirish", "Кириш", "Войти"),
        ["LoginShior"] = ("Shoxobcha savdosi, smenalar va operatorlar — bir ekranda, real vaqtda.", "Шохобча савдоси, сменалар ва операторлар — бир экранда, реал вақтда.", "Продажи АЗС, смены и операторы — на одном экране, в реальном времени."),
        ["SmenaKamomati"] = ("Smena kamomati", "Смена камомати", "Недостача смены"),
        ["OperatorHisobi"] = ("Operator hisobi", "Оператор ҳисоби", "Счёт оператора"),
        ["Soni"] = ("Soni", "Сони", "Кол-во"),
        ["LoginniKiriting"] = ("Loginni kiriting", "Логинни киритинг", "Введите логин"),
        ["OxirgiKirganlar"] = ("Shu kompyuterda kirganlar", "Шу компьютерда кирганлар", "Входили на этом компьютере"),
        ["ServerManzili"] = ("Server manzili", "Сервер манзили", "Адрес сервера"),
        ["ServerIzoh"] = ("Server: {0}", "Сервер: {0}", "Сервер: {0}"),
        ["Yuklanmoqda"] = ("Ulanmoqda…", "Уланмоқда…", "Подключение…"),
        ["Xato_ServerManzil"] = ("Server manzili noto'g'ri (masalan: http://192.168.1.10:5000)", "Сервер манзили нотўғри (масалан: http://192.168.1.10:5000)", "Неверный адрес сервера (например: http://192.168.1.10:5000)"),
        ["AloqaYoq"] = ("Server bilan aloqa yo'q", "Сервер билан алоқа йўқ", "Нет связи с сервером"),
        ["SessiyaTugadi"] = ("Sessiya tugadi — qayta kiring", "Сессия тугади — қайта киринг", "Сессия истекла — войдите снова"),
        ["ServerXatosi"] = ("Server xatosi ({0})", "Сервер хатоси ({0})", "Ошибка сервера ({0})"),
        ["XatoSarlavha"] = ("Amal bajarilmadi", "Амал бажарилмади", "Действие не выполнено"),
        ["Malumot"] = ("Ma'lumot", "Маълумот", "Информация"),
        ["ZaxiraServerda"] = ("Zaxira nusxalar serverda saqlanadi (/data/zaxira, 30 kun). Nusxani olish uchun server administratoriga murojaat qiling.", "Захира нусхалар серверда сақланади (/data/zaxira, 30 кун). Нусхани олиш учун сервер администраторига мурожаат қилинг.", "Резервные копии хранятся на сервере (/data/zaxira, 30 дней). Для получения копии обратитесь к администратору сервера."),
        ["Xato_Pin"] = ("PIN 4–6 raqamdan iborat bo'lishi kerak", "PIN 4–6 рақамдан иборат бўлиши керак", "PIN должен содержать 4–6 цифр"),

        // ---- Boshqaruv paneli
        ["Yangilash"] = ("Yangilash", "Янгилаш", "Обновить"),
        ["ShuOyKamomat"] = ("Shu oy kamomat", "Шу ой камомат", "Недостача за месяц"),

        // ---- Sotuv kiritish
        ["SmenaOchiq"] = ("smena ochiq", "смена очиқ", "смена открыта"),
        ["SmenaYopiq"] = ("smena yopiq", "смена ёпиқ", "смена закрыта"),
        ["TolovTuri"] = ("To'lov turi", "Тўлов тури", "Вид оплаты"),
        ["Qoldiq"] = ("Qoldiq", "Қолдиқ", "Остаток"),
        ["Narx"] = ("Narx", "Нарх", "Цена"),
        ["JamiSumma"] = ("Jami summa", "Жами сумма", "Итого"),

        // ---- Smenalar
        ["Bugun"] = ("Bugun", "Бугун", "Сегодня"),
        ["Hammasi"] = ("Hammasi", "Ҳаммаси", "Все"),
        ["Boshlandi"] = ("Boshlandi", "Бошланди", "Начало"),
        ["Davomiylik"] = ("Davomiylik", "Давомийлик", "Длительность"),
        ["Farq"] = ("Farq", "Фарқ", "Разница"),
        ["Ochiq"] = ("Ochiq", "Очиқ", "Открыта"),
        ["Yopilgan"] = ("Yopilgan", "Ёпилган", "Закрыта"),
        ["Kutilgan"] = ("Kutilgan", "Кутилган", "Ожидается"),
        ["FarqYoq"] = ("Farq yo'q — smena aniq topshirildi", "Фарқ йўқ — смена аниқ топширилди", "Разницы нет — смена сдана точно"),

        // ---- Hisobotlar
        ["Davr"] = ("Davr", "Давр", "Период"),
        ["Dan"] = ("Dan", "Дан", "С"),
        ["Gacha"] = ("Gacha", "Гача", "По"),
        ["Oylik"] = ("Oylik", "Ойлик", "По месяцам"),
        ["TezDavr"] = ("Tez davr:", "Тез давр:", "Быстрый период:"),
        ["JamiSavdo"] = ("Jami savdo", "Жами савдо", "Всего продаж"),
        ["Avans"] = ("Avans", "Аванс", "Аванс"),
        ["Bekor"] = ("bekor", "бекор", "отменено"),

        // ---- Operatorlar
        ["Maosh"] = ("Maosh", "Маош", "Оклад"),
        ["JoriyQoldiq"] = ("Joriy qoldiq", "Жорий қолдиқ", "Текущий остаток"),
        ["HisobVaraqa"] = ("Hisob-varaqa", "Ҳисоб-варақа", "Выписка"),
        ["Kamomat"] = ("Kamomat", "Камомат", "Недостача"),
        ["Ortiqcha"] = ("Ortiqcha", "Ортиқча", "Излишек"),
        ["Turi"] = ("Turi", "Тури", "Тип"),
        ["KimYozdi"] = ("Kim yozdi", "Ким ёзди", "Кто записал"),
        ["PulBerish"] = ("Pul berish", "Пул бериш", "Выдача денег"),
        ["MaoshTolovi"] = ("Maosh to'lovi", "Маош тўлови", "Выплата оклада"),
        ["SummaSom"] = ("Summa (so'm)", "Сумма (сўм)", "Сумма (сум)"),
        ["IzohMisol2"] = ("Masalan: oilaviy ehtiyoj uchun", "Масалан: оилавий эҳтиёж учун", "Например: на семейные нужды"),
        ["H_Maosh"] = ("Oylik maosh", "Ойлик маош", "Оклад"),
        ["H_Avans"] = ("Avans", "Аванс", "Аванс"),
        ["H_Kamomat"] = ("Kamomat", "Камомат", "Недостача"),
        ["H_Ortiqcha"] = ("Ortiqcha", "Ортиқча", "Излишек"),
        ["H_Tolov"] = ("To'lov", "Тўлов", "Выплата"),
        ["MaoshBerildi"] = ("Maosh berildi", "Маош берилди", "Оклад выплачен"),

        // ---- Sozlamalar
        ["SozlamalarIzoh"] = ("Narxlar, aparatlar, foydalanuvchilar, ruxsatlar va zaxira nusxa", "Нархлар, апаратлар, фойдаланувчилар, рухсатлар ва захира нусха", "Цены, колонки, пользователи, права и резервная копия"),
        ["YoqilgiNarxlari"] = ("Yoqilg'i narxlari", "Ёқилғи нархлари", "Цены на топливо"),
        ["Aparatlar"] = ("Aparatlar", "Апаратлар", "Колонки"),
        ["Foydalanuvchilar"] = ("Foydalanuvchilar", "Фойдаланувчилар", "Пользователи"),
        ["Ruxsatlar"] = ("Ruxsatlar", "Рухсатлар", "Права"),
        ["ZaxiraNusxa"] = ("Zaxira nusxa", "Захира нусха", "Резервная копия"),
        ["Joriy"] = ("Joriy", "Жорий", "Текущая"),
        ["YangiNarx"] = ("Yangi narx", "Янги нарх", "Новая цена"),
        ["NarxTarixi"] = ("Narx tarixi", "Нарх тарихи", "История цен"),
        ["Eski"] = ("Eski", "Эски", "Старая"),
        ["Yangi"] = ("Yangi", "Янги", "Новая"),
        ["AparatQoshish"] = ("Aparat qo'shish", "Апарат қўшиш", "Добавить колонку"),
        ["AparatlarIzoh"] = ("Har aparat bitta yoqilg'i turiga bog'lanadi. Keyinroq BeiLin pultlari shu aparatlarga ulanadi.", "Ҳар апарат битта ёқилғи турига боғланади. Кейинроқ BeiLin пультлари шу апаратларга уланади.", "Каждая колонка привязана к одному виду топлива. Позже к ним подключатся пульты BeiLin."),
        ["FoydalanuvchiQoshish"] = ("Foydalanuvchi qo'shish", "Фойдаланувчи қўшиш", "Добавить пользователя"),
        ["ToliqIsm"] = ("To'liq ism", "Тўлиқ исм", "Полное имя"),
        ["Login"] = ("Login", "Логин", "Логин"),
        ["Rol"] = ("Rol", "Рол", "Роль"),
        ["OylikMaosh"] = ("Oylik maosh", "Ойлик маош", "Оклад"),
        ["Holat"] = ("Holat", "Ҳолат", "Статус"),
        ["Faol"] = ("Faol", "Фаол", "Активен"),
        ["PinParolTiklash"] = ("PIN/parolni tiklash", "PIN/паролни тиклаш", "Сбросить PIN/пароль"),
        ["AvtomatikNusxa"] = ("Server kuniga bir marta nusxa oladi", "Сервер кунига бир марта нусха олади", "Сервер делает копию раз в день"),
        ["NusxaIzoh"] = ("Avtomatik, serverda (/data/zaxira); oxirgi 30 kun saqlanadi", "Автоматик, серверда (/data/zaxira); охирги 30 кун сақланади", "Автоматически, на сервере (/data/zaxira); хранятся последние 30 дней"),
        ["OxirgiNusxa"] = ("Oxirgi nusxa", "Охирги нусха", "Последняя копия"),
        ["OxirgiNusxaIzoh"] = ("Shu sessiyada qo'lda nusxa olinmagan", "Шу сессияда қўлда нусха олинмаган", "В этом сеансе копия вручную не создавалась"),
        ["HozirNusxa"] = ("Hozir nusxa olish", "Ҳозир нусха олиш", "Создать копию сейчас"),
        ["NusxadanTiklash"] = ("Nusxadan tiklash…", "Нусхадан тиклаш…", "Восстановить из копии…"),
        ["PapkaniOchish"] = ("Papkani ochish", "Папкани очиш", "Открыть папку"),

        // Ruxsat nomlari va izohlari
        ["Hozirgi"] = ("Hozirgi", "Ҳозирги", "Текущее"),

        // ---- Audit
        ["Amal"] = ("Amal", "Амал", "Действие"),
        ["Tafsilot"] = ("Tafsilot", "Тафсилот", "Детали"),
        ["Sabab"] = ("Sabab", "Сабаб", "Причина"),

        // ---- Umumiy kalitlar: desktop ishlatmaydi, web ishlatadi (Til.cs — yagona manba)
        ["Bolimlar"] = ("Bo'limlar", "Бўлимлар", "Разделы"),
        ["Kirill"] = ("O'zbek (kirill)", "Ўзбек (кирилл)", "Узбекский (кир.)"),
        ["Lotin"] = ("O'zbek (lotin)", "Ўзбек (лотин)", "Узбекский (лат.)"),
        ["NusxaOlindi"] = ("Nusxa olindi", "Нусха олинди", "Копия создана"),
        ["PinTiklandi"] = ("PIN/parol yangilandi", "PIN/парол янгиланди", "PIN/пароль обновлён"),
        ["Qidirish"] = ("Qidirish…", "Қидириш…", "Поиск…"),
        ["Rus"] = ("Ruscha", "Русча", "Русский"),
        ["Saqlandi"] = ("Saqlandi", "Сақланди", "Сохранено"),
        ["TaAparat"] = ("ta aparat", "та апарат", "колонок"),
        ["Tolov"] = ("To'lov", "Тўлов", "Оплата"),

        // ---- Smena hisobi: faqat desktop'da (web'da yo'q)
        ["Nasiya_XatoTelefon"] = ("Telefon raqamini to'liq yozing: +998 XX XXX XX XX", "Телефон рақамини тўлиқ ёзинг: +998 XX XXX XX XX", "Введите номер полностью: +998 XX XXX XX XX"),
        ["Nasiya_MavjudMijoz"] = ("Mavjud mijoz · faol qarz {0}", "Мавжуд мижоз · фаол қарз {0}", "Существующий клиент · активный долг {0}"),
        ["Nasiya_MavjudMijozlar"] = ("Mavjud mijozlar", "Мавжуд мижозлар", "Существующие клиенты"),
        ["Nasiya_TaklifQarz"] = ("qarz {0}", "қарз {0}", "долг {0}"),
        ["Nasiya_TaklifQarzYoq"] = ("qarzi yo'q", "қарзи йўқ", "без долга"),
        ["Nasiyalar_JamiQarzdorlik"] = ("Jami qarzdorlik", "Жами қарздорлик", "Общая задолженность"),
        ["Nasiyalar_JamiQarzIzoh"] = ("{0} ta mijoz · shundan muddati o'tgan {1}", "{0} та мижоз · шундан муддати ўтган {1}", "Клиентов: {0} · из них просрочено {1}"),
        ["Nasiyalar_Excel"] = ("Excel", "Excel", "Excel"),
        ["Nasiyalar_ExcelSarlavha"] = ("Nasiyalar", "Насиялар", "Долги"),
        ["Nasiyalar_ColSmena"] = ("Smena", "Смена", "Смена"),
        ["Nasiyalar_ColHolat"] = ("Holat", "Ҳолат", "Статус"),
        ["Savdo_JamiQarzdorlik"] = ("Jami qarzdorlik {0} · {1} ta mijoz", "Жами қарздорлик {0} · {1} та мижоз", "Общая задолженность {0} · клиентов: {1}"),
        ["Boshqaruv_NasiyaQarzdorligi"] = ("Nasiya qarzdorligi", "Насия қарздорлиги", "Задолженность по долгам"),
        ["Boshqaruv_OtganQarzQisqa"] = ("muddati o'tgan {0} · {1} ta", "муддати ўтган {0} · {1} та", "просрочено {0} · {1}"),
        ["Bosh_AparatYoq"] = ("Hali aparat qo'shilmagan. Smena ochishdan oldin Sozlamalar'da yoqilg'i, keyin aparat (boshlang'ich pult ko'rsatkichi va bak qoldig'i bilan) qo'shilishi kerak — buni administrator sozlaydi.",
                              "Ҳали апарат қўшилмаган. Смена очишдан олдин Созламалар'да ёқилғи, кейин апарат (бошланғич пульт кўрсаткичи ва бак қолдиғи билан) қўшилиши керак — буни администратор созлайди.",
                              "Колонки ещё не добавлены. Перед открытием смены в Настройках нужно добавить топливо, затем колонку (с начальным показанием пульта и остатком бака) — это настраивает администратор."),
        ["Bosh_YoqilgiYoq"] = ("Avval «Yoqilg'i narxlari» bo'limida yoqilg'i qo'shing — har bir aparat bitta yoqilg'iga bog'lanadi.",
                               "Аввал «Ёқилғи нархлари» бўлимида ёқилғи қўшинг — ҳар бир апарат битта ёқилғига боғланади.",
                               "Сначала добавьте топливо в разделе «Цены на топливо» — каждая колонка привязана к одному виду топлива."),
        ["Sozlama_AparatSoni"] = ("{0} ta aparat", "{0} та апарат", "Колонок: {0}"),
        ["Hisobot_KpiXarajatYozuv"] = ("{0} ta yozuv", "{0} та ёзув", "Записей: {0}"),

        // ==== Smena hisobi: web lugat-web.json bilan bir xil kalitlar (generatsiya) — BOSHI
        ["QaytaUlanmoqda"] = ("Server bilan qayta ulanmoqda…", "Сервер билан қайта уланмоқда…", "Переподключение к серверу…"),
        ["EslabQol"] = ("Eslab qolish", "Эслаб қолиш", "Запомнить меня"),
        ["LoginKiriting"] = ("Loginni kiriting", "Логинни киритинг", "Введите логин"),
        ["PinKlaviatura"] = ("PIN klaviatura", "PIN клавиатура", "PIN-клавиатура"),
        ["Xato_Login"] = ("Login yoki parol noto'g'ri", "Логин ёки парол нотўғри", "Неверный логин или пароль"),
        ["Yana"] = ("Yana", "Яна", "Ещё"),
        ["MalumotYoq"] = ("Ma'lumot yo'q", "Маълумот йўқ", "Нет данных"),
        ["Xato_Umumiy"] = ("Xatolik yuz berdi", "Хатолик юз берди", "Произошла ошибка"),
        ["Xato_Summa"] = ("Summa yoki litrni kiriting", "Сумма ёки литрни киритинг", "Введите сумму или литры"),
        ["MeningHisobim"] = ("Mening hisobim", "Менинг ҳисобим", "Мой счёт"),
        ["Yorug"] = ("Yorug'", "Ёруғ", "Светлая"),
        ["Qorongi"] = ("Qorong'i", "Қоронғи", "Тёмная"),
        ["Tizim"] = ("Tizim", "Тизим", "Системная"),
        ["Versiya"] = ("Versiya", "Версия", "Версия"),
        ["YangiVersiya"] = ("Yangi versiya tayyor", "Янги версия тайёр", "Доступна новая версия"),
        ["Yangilash2"] = ("Yangilash", "Янгилаш", "Обновить"),
        ["OyNomlari"] = ("Yanvar,Fevral,Mart,Aprel,May,Iyun,Iyul,Avgust,Sentabr,Oktabr,Noyabr,Dekabr", "Январ,Феврал,Март,Апрел,Май,Июн,Июл,Август,Сентябр,Октябр,Ноябр,Декабр", "Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь"),
        ["IlovaniOrnatish"] = ("Ilovani o'rnatish", "Иловани ўрнатиш", "Установить приложение"),
        ["OrnatishIzoh"] = ("Bosh ekranga qo'shing — ilova kabi tez ochiladi va internetsiz ham ishlaydi", "Бош экранга қўшинг — илова каби тез очилади ва интернетсиз ҳам ишлайди", "Добавьте на главный экран — открывается как приложение и работает без интернета"),
        ["IosOrnatish1"] = ("Safari pastidagi «Ulashish» tugmasini bosing", "Safari пастидаги «Улашиш» тугмасини босинг", "Нажмите «Поделиться» внизу Safari"),
        ["IosOrnatish2"] = ("«Bosh ekranga qo'shish» ni tanlang", "«Бош экранга қўшиш» ни танланг", "Выберите «На экран „Домой“»"),
        ["Keyinroq"] = ("Keyinroq", "Кейинроқ", "Позже"),
        ["IlovaOrnatilgan"] = ("Ilova o'rnatilgan", "Илова ўрнатилган", "Приложение установлено"),
        ["Tab_Hisobot"] = ("Hisobot", "Ҳисобот", "Отчёты"),
        ["Tab_Operator"] = ("Operator", "Оператор", "Операторы"),
        ["HammasiniKorsat"] = ("Hammasini ko'rsatish", "Ҳаммасини кўрсатиш", "Показать все"),
        ["Ornatish"] = ("O'rnatish", "Ўрнатиш", "Установить"),
        ["Boshqaruv_Sarlavha"] = ("Boshqaruv paneli", "Бошқарув панели", "Панель управления"),
        ["Boshqaruv_OylikHisobot"] = ("Oylik hisobot", "Ойлик ҳисобот", "Отчёт за месяц"),
        ["Boshqaruv_OxirgiSmenaSavdosi"] = ("Oxirgi smena savdosi", "Охирги смена савдоси", "Продажи за последнюю смену"),
        ["Boshqaruv_OxirgiSmenaIzoh"] = ("#{0} · {1} · {2} L", "#{0} · {1} · {2} Л", "№{0} · {1} · {2} л"),
        ["Boshqaruv_YopilganYoq"] = ("Yopilgan smena yo'q", "Ёпилган смена йўқ", "Закрытых смен нет"),
        ["Boshqaruv_OySavdo"] = ("Shu oy savdo", "Шу ой савдо", "Продажи за месяц"),
        ["Boshqaruv_OySmenaIzoh"] = ("{0} ta yopilgan smena · {1} L", "{0} та ёпилган смена · {1} Л", "Закрытых смен: {0} · {1} л"),
        ["Boshqaruv_OrtiqchaIzoh"] = ("Ortiqcha {0} · {1} smenada", "Ортиқча {0} · {1} сменада", "Излишек {0} · смен: {1}"),
        ["Boshqaruv_OrtiqchaYoq"] = ("Ortiqcha yo'q", "Ортиқча йўқ", "Излишка нет"),
        ["Boshqaruv_MuddatiOtganNasiya"] = ("Muddati o'tgan nasiya", "Муддати ўтган насия", "Просроченные долги"),
        ["Boshqaruv_QarzIzoh"] = ("{0} ta mijoz · jami qarz {1}", "{0} та мижоз · жами қарз {1}", "Клиентов: {0} · всего долга {1}"),
        ["Boshqaruv_JoriySmena"] = ("Joriy smena #{0} · {1}", "Жорий смена #{0} · {1}", "Текущая смена №{0} · {1}"),
        ["Boshqaruv_Smenada"] = ("Smenada", "Сменада", "На смене"),
        ["Boshqaruv_BoshlanganDavomiylik"] = ("{0} dan · {1}", "{0} дан · {1}", "с {0} · {1}"),
        ["Boshqaruv_QaytimPuli"] = ("Qaytim puli", "Қайтим пули", "Деньги на сдачу"),
        ["Boshqaruv_TerminalOchishda"] = ("Terminal, ochishda", "Терминал, очишда", "Терминал, при открытии"),
        ["Boshqaruv_DepozitOchishda"] = ("Depozit, ochishda", "Депозит, очишда", "Депозит, при открытии"),
        ["Boshqaruv_NasiyaSoni"] = ("Nasiya · {0} ta", "Насия · {0} та", "Долги · {0}"),
        ["Boshqaruv_QaytganNasiya"] = ("Qaytgan nasiya", "Қайтган насия", "Возвращённые долги"),
        ["Boshqaruv_XarajatSoni"] = ("Xarajat · {0} ta", "Харажат · {0} та", "Расходы · {0}"),
        ["Boshqaruv_OchiqSmenaIzoh"] = ("Ochiq smenaning savdosi yopilganda pult ko'rsatkichlaridan hisoblanadi. Hozircha faqat nasiya va xarajatlar ko'rinadi.", "Очиқ сменанинг савдоси ёпилганда пулт кўрсаткичларидан ҳисобланади. Ҳозирча фақат насия ва харажатлар кўринади.", "Продажи открытой смены считаются по показаниям пультов при закрытии. Пока видны только долги и расходы."),
        ["Boshqaruv_SmenaYopiq"] = ("Smena yopiq", "Смена ёпиқ", "Смена закрыта"),
        ["Boshqaruv_Yopiq"] = ("Yopiq", "Ёпиқ", "Закрыта"),
        ["Boshqaruv_OchiqSmenaYoq"] = ("Hozir ochiq smena yo'q. Smena Savdo bo'limida ochiladi.", "Ҳозир очиқ смена йўқ. Смена Савдо бўлимида очилади.", "Сейчас нет открытой смены. Смена открывается в разделе «Продажи»."),
        ["Boshqaruv_SmenaOchish"] = ("Smenani ochish", "Сменани очиш", "Открыть смену"),
        ["Boshqaruv_OxirgiSmena"] = ("Oxirgi smena #{0}", "Охирги смена #{0}", "Последняя смена №{0}"),
        ["Boshqaruv_Yopildi"] = ("Yopilgan vaqti", "Ёпилган вақти", "Время закрытия"),
        ["Boshqaruv_BaklarQoldigi"] = ("Baklar qoldig'i", "Баклар қолдиғи", "Остатки в баках"),
        ["Boshqaruv_HolatigaVaqt"] = ("{0} holatiga", "{0} ҳолатига", "на {0}"),
        ["Boshqaruv_KirimSana"] = ("kirim {0}", "кирим {0}", "приход {0}"),
        ["Boshqaruv_OxirgiSmenalarSavdosi"] = ("Oxirgi 14 smena savdosi", "Охирги 14 смена савдоси", "Продажи за последние 14 смен"),
        ["Boshqaruv_MillionSom"] = ("million so'm", "миллион сўм", "млн сум"),
        ["Boshqaruv_TolovTurlari"] = ("To'lov turlari · shu oy", "Тўлов турлари · шу ой", "Виды оплаты · этот месяц"),
        ["Boshqaruv_OxirgiYopilganSmenalar"] = ("Oxirgi yopilgan smenalar", "Охирги ёпилган сменалар", "Последние закрытые смены"),
        ["Boshqaruv_BarchaSmenalar"] = ("Barcha smenalar", "Барча сменалар", "Все смены"),
        ["Boshqaruv_FarqYoq"] = ("Farq yo'q", "Фарқ йўқ", "Без разницы"),
        ["Boshqaruv_Soat"] = ("{0} soat", "{0} соат", "{0} ч"),
        ["Boshqaruv_SoatDaqiqa"] = ("{0} soat {1} daqiqa", "{0} соат {1} дақиқа", "{0} ч {1} мин"),
        ["Boshqaruv_Daqiqa"] = ("{0} daqiqa", "{0} дақиқа", "{0} мин"),
        ["Boshqaruv_HaftaKunlari"] = ("Yakshanba,Dushanba,Seshanba,Chorshanba,Payshanba,Juma,Shanba", "Якшанба,Душанба,Сешанба,Чоршанба,Пайшанба,Жума,Шанба", "Воскресенье,Понедельник,Вторник,Среда,Четверг,Пятница,Суббота"),
        ["Boshqaruv_OyNomlari"] = ("yanvar,fevral,mart,aprel,may,iyun,iyul,avgust,sentabr,oktabr,noyabr,dekabr", "январ,феврал,март,апрел,май,июн,июл,август,сентабр,октабр,ноябр,декабр", "января,февраля,марта,апреля,мая,июня,июля,августа,сентября,октября,ноября,декабря"),
        ["Tolov_Nasiya"] = ("Nasiya", "Насия", "В долг"),
        ["Boshqaruv_SanaShakli"] = ("{0}, {1}-{2} {3}", "{0}, {1}-{2} {3}", "{0}, {1} {2} {3}"),
        ["Smenalar_Davr"] = ("Davr", "Давр", "Период"),
        ["Smenalar_Davr7Kun"] = ("7 kun", "7 кун", "7 дней"),
        ["Smenalar_DavrShuOy"] = ("Shu oy", "Шу ой", "Этот месяц"),
        ["Smenalar_DavrOtganOy"] = ("O'tgan oy", "Ўтган ой", "Прошлый месяц"),
        ["Smenalar_Operator"] = ("Operator", "Оператор", "Оператор"),
        ["Smenalar_BarchaOperatorlar"] = ("Barcha operatorlar", "Барча операторлар", "Все операторы"),
        ["Smenalar_Joriy"] = ("Joriy smena #{0} · {1} · {2} dan", "Жорий смена #{0} · {1} · {2} дан", "Текущая смена №{0} · {1} · с {2}"),
        ["Smenalar_JoriyYoq"] = ("Hozir ochiq smena yo'q", "Ҳозир очиқ смена йўқ", "Сейчас нет открытой смены"),
        ["Smenalar_KpiOchiq"] = ("Hozir ochiq", "Ҳозир очиқ", "Сейчас открыто"),
        ["Smenalar_OchiqYoq"] = ("Ochiq smena yo'q", "Очиқ смена йўқ", "Открытой смены нет"),
        ["Smenalar_KpiSoni7Kun"] = ("Oxirgi 7 kun smenalari", "Охирги 7 кун сменалари", "Смены за 7 дней"),
        ["Smenalar_KpiSoniShuOy"] = ("Shu oy smenalar", "Шу ой сменалар", "Смены за месяц"),
        ["Smenalar_KpiSoniOtganOy"] = ("O'tgan oy smenalar", "Ўтган ой сменалар", "Смены за прошлый месяц"),
        ["Smenalar_KpiSoniIzoh"] = ("{0} ta yopilgan, {1} ta ochiq", "{0} та ёпилган, {1} та очиқ", "закрыто {0}, открыто {1}"),
        ["Smenalar_KpiKamomat7Kun"] = ("7 kun kamomat", "7 кун камомат", "Недостача за 7 дней"),
        ["Smenalar_KpiKamomatShuOy"] = ("Shu oy kamomat", "Шу ой камомат", "Недостача за месяц"),
        ["Smenalar_KpiKamomatOtganOy"] = ("O'tgan oy kamomat", "Ўтган ой камомат", "Недостача за прошлый месяц"),
        ["Smenalar_KpiKamomatIzoh"] = ("Ortiqcha {0}", "Ортиқча {0}", "Излишек {0}"),
        ["Smenalar_Royxat7Kun"] = ("Oxirgi 7 kun smenalari", "Охирги 7 кун сменалари", "Смены за последние 7 дней"),
        ["Smenalar_RoyxatOy"] = ("{0} smenalari", "{0} сменалари", "Смены — {0}"),
        ["Smenalar_ColRaqam"] = ("#", "#", "№"),
        ["Smenalar_ColOchildi"] = ("Ochildi", "Очилди", "Открыта"),
        ["Smenalar_ColLitr"] = ("Litr", "Литр", "Литры"),
        ["Smenalar_ColSavdo"] = ("Savdo", "Савдо", "Продажи"),
        ["Smenalar_ColFarq"] = ("Farq", "Фарқ", "Разница"),
        ["Smenalar_Yopilmagan"] = ("yopilmagan", "ёпилмаган", "не закрыта"),
        ["Smenalar_Ochiq"] = ("Ochiq", "Очиқ", "Открыта"),
        ["Smenalar_Yopilgan"] = ("Yopilgan", "Ёпилган", "Закрыта"),
        ["Smenalar_Bosh"] = ("Bu davrda smena yo'q", "Бу даврда смена йўқ", "За этот период смен нет"),
        ["Smenalar_Tanlang"] = ("Smenani tanlang", "Сменани танланг", "Выберите смену"),
        ["Smenalar_Smena"] = ("Smena #{0}", "Смена #{0}", "Смена №{0}"),
        ["Smenalar_DavomiYopilgan"] = ("{0} · {1} dan {2} gacha", "{0} · {1} дан {2} гача", "{0} · с {1} до {2}"),
        ["Smenalar_DavomiOchiq"] = ("{0} · {1} dan · davom etmoqda", "{0} · {1} дан · давом этмоқда", "{0} · с {1} · идёт"),
        ["Smenalar_Davomiylik"] = ("{0} soat {1} daqiqa", "{0} соат {1} дақиқа", "{0} ч {1} мин"),
        ["Smenalar_OchiqIzoh"] = ("Smena ochiq: savdo yopilganda pult ko'rsatkichlaridan hisoblanadi. Hozircha faqat qoldiqlar, nasiya va xarajatlar ko'rinadi.", "Смена очиқ: савдо ёпилганда пулт кўрсаткичларидан ҳисобланади. Ҳозирча фақат қолдиқлар, насия ва харажатлар кўринади.", "Смена открыта: продажи считаются по показаниям пульта при закрытии. Пока видны только остатки, долги и расходы."),
        ["Smenalar_OchishdagiQoldiqlar"] = ("Ochilgandagi qoldiqlar", "Очилгандаги қолдиқлар", "Остатки при открытии"),
        ["Smenalar_Terminal"] = ("Terminal · plastik", "Терминал · пластик", "Терминал · пластик"),
        ["Smenalar_DepozitKarta"] = ("Depozit karta", "Депозит карта", "Депозитная карта"),
        ["Smenalar_Aparatlar"] = ("Aparat ko'rsatkichlari", "Аппарат кўрсаткичлари", "Показания аппаратов"),
        ["Smenalar_Aparat"] = ("Aparat", "Аппарат", "Аппарат"),
        ["Smenalar_Oldingi"] = ("Oldingi", "Олдинги", "Было"),
        ["Smenalar_Yangi"] = ("Yangi", "Янги", "Стало"),
        ["Smenalar_Litr"] = ("Litr", "Литр", "Литры"),
        ["Smenalar_Summa"] = ("Summa", "Сумма", "Сумма"),
        ["Smenalar_Narx"] = ("Narx", "Нарх", "Цена"),
        ["Smenalar_PulHisobi"] = ("Pul hisobi", "Пул ҳисоби", "Денежный расчёт"),
        ["Smenalar_Qaytim"] = ("Qaytim puli, ochishda", "Қайтим пули, очишда", "Размен при открытии"),
        ["Smenalar_SavdoAparatlar"] = ("Savdo, aparatlar", "Савдо, аппаратлар", "Продажи по аппаратам"),
        ["Smenalar_QaytganNasiya"] = ("Qaytgan nasiya", "Қайтган насия", "Возвращённые долги"),
        ["Smenalar_PlastikSatr"] = ("Plastik: {0} − {1}", "Пластик: {0} − {1}", "Пластик: {0} − {1}"),
        ["Smenalar_DepozitSatr"] = ("Depozit: {0} dan {1} ga", "Депозит: {0} дан {1} га", "Депозит: с {0} на {1}"),
        ["Smenalar_NasiyaSatr"] = ("Nasiya · {0}", "Насия · {0}", "Долг · {0}"),
        ["Smenalar_XarajatSatr"] = ("Xarajat · {0}", "Харажат · {0}", "Расход · {0}"),
        ["Smenalar_NasiyalarJami"] = ("Nasiya (jami)", "Насия (жами)", "Долги (итого)"),
        ["Smenalar_XarajatlarJami"] = ("Xarajatlar (jami)", "Харажатлар (жами)", "Расходы (итого)"),
        ["Smenalar_KassadaKerak"] = ("Kassada bo'lishi kerak", "Кассада бўлиши керак", "Должно быть в кассе"),
        ["Smenalar_SanalganNaqd"] = ("Sanalgan naqd", "Саналган нақд", "Пересчитанные наличные"),
        ["Smenalar_FarqYoq"] = ("Farq yo'q, kassa to'g'ri", "Фарқ йўқ, касса тўғри", "Разницы нет, касса сходится"),
        ["Smenalar_Kamomat"] = ("Kamomat", "Камомат", "Недостача"),
        ["Smenalar_Ortiqcha"] = ("Ortiqcha", "Ортиқча", "Излишек"),
        ["Smenalar_KamomatIzoh"] = ("{0} oyligidan ayiriladi", "{0} ойлигидан айирилади", "удерживается из зарплаты: {0}"),
        ["Smenalar_OrtiqchaIzoh"] = ("{0} hisobiga yoziladi", "{0} ҳисобига ёзилади", "записывается на счёт: {0}"),
        ["Smenalar_Izoh"] = ("Izoh", "Изоҳ", "Комментарий"),
        ["Smenalar_Nasiyalar"] = ("Nasiya berildi", "Насия берилди", "Выдано в долг"),
        ["Smenalar_Qaytishlar"] = ("Qaytgan nasiya", "Қайтган насия", "Возвраты долгов"),
        ["Smenalar_Xarajatlar"] = ("Xarajatlar", "Харажатлар", "Расходы"),
        ["Smenalar_MuddatGacha"] = ("{0} gacha", "{0} гача", "до {0}"),
        ["Smenalar_ManbaKassa"] = ("kassadan", "кассадан", "из кассы"),
        ["Smenalar_ManbaDepozit"] = ("depozit kartadan", "депозит картадан", "с депозитной карты"),
        ["Smenalar_Ochirish"] = ("O'chirish", "Ўчириш", "Удалить"),
        ["Smenalar_OchirishTasdiq"] = ("Aniq o'chirilsinmi?", "Аниқ ўчирилсинми?", "Точно удалить?"),
        ["Smenalar_Ochirildi"] = ("O'chirildi", "Ўчирилди", "Удалено"),
        ["Smenalar_Tuzatish"] = ("Ko'rsatkichni tuzatish", "Кўрсаткични тузатиш", "Исправить показание"),
        ["Smenalar_Excel"] = ("Excel", "Excel", "Excel"),
        ["Smenalar_TuzatishIzoh"] = ("Tuzatishni faqat boshliq qiladi. Sabab majburiy yoziladi, smena hisobi qayta chiqadi va auditga tushadi.", "Тузатишни фақат бошлиқ қилади. Сабаб мажбурий ёзилади, смена ҳисоби қайта чиқади ва аудитга тушади.", "Исправление делает только начальник. Причина обязательна, расчёт смены пересчитывается и попадает в аудит."),
        ["Smenalar_TuzatishSarlavha"] = ("Ko'rsatkichni tuzatish", "Кўрсаткични тузатиш", "Исправление показания"),
        ["Smenalar_TuzatishQaysi"] = ("Qaysi aparat", "Қайси аппарат", "Какой аппарат"),
        ["Smenalar_TuzatishBoshi"] = ("Smena boshidagi", "Смена бошидаги", "На начало"),
        ["Smenalar_TuzatishJoriy"] = ("Hozirgi ko'rsatkich", "Ҳозирги кўрсаткич", "Текущее показание"),
        ["Smenalar_TuzatishYangi"] = ("Yangi ko'rsatkich, L", "Янги кўрсаткич, Л", "Новое показание, л"),
        ["Smenalar_TuzatishNatija"] = ("Shu aparatda sotilgan {0} L = {1} so'm. Tuzatishdan keyin kassada bo'lishi kerak: {2}, farq: {3}.", "Шу аппаратда сотилган {0} Л = {1} сўм. Тузатишдан кейин кассада бўлиши керак: {2}, фарқ: {3}.", "Продано по аппарату {0} л = {1} сум. После исправления в кассе должно быть: {2}, разница: {3}."),
        ["Smenalar_TuzatishSabab"] = ("Tuzatish sababi", "Тузатиш сабаби", "Причина исправления"),
        ["Smenalar_TuzatishSababPlaceholder"] = ("Masalan: yozishda xato", "Масалан: ёзишда хато", "Например: ошибка при вводе"),
        ["Smenalar_TuzatishXatoQiymat"] = ("Yangi ko'rsatkichni yozing", "Янги кўрсаткични ёзинг", "Укажите новое показание"),
        ["Smenalar_TuzatishXatoKichik"] = ("Yangi ko'rsatkich {0} dan kichik bo'lmasligi kerak", "Янги кўрсаткич {0} дан кичик бўлмаслиги керак", "Новое показание не может быть меньше {0}"),
        ["Smenalar_TuzatishXatoSabab"] = ("Tuzatish sababini yozing", "Тузатиш сабабини ёзинг", "Укажите причину исправления"),
        ["Hisobot_Excel"] = ("Excel", "Excel", "Excel"),
        ["Hisobot_Filtrlar"] = ("Filtrlar", "Филтрлар", "Фильтры"),
        ["Hisobot_Dan"] = ("Dan", "Дан", "С"),
        ["Hisobot_Gacha"] = ("Gacha", "Гача", "По"),
        ["Hisobot_Operator"] = ("Operator", "Оператор", "Оператор"),
        ["Hisobot_Hammasi"] = ("Hammasi", "Ҳаммаси", "Все"),
        ["Hisobot_Guruhlash"] = ("Guruhlash", "Гуруҳлаш", "Группировка"),
        ["Hisobot_GuruhSmena"] = ("Smena", "Смена", "Смена"),
        ["Hisobot_GuruhKun"] = ("Kunlik", "Кунлик", "По дням"),
        ["Hisobot_GuruhOy"] = ("Oylik", "Ойлик", "По месяцам"),
        ["Hisobot_GuruhOperator"] = ("Operator", "Оператор", "Оператор"),
        ["Hisobot_TezDavr"] = ("Tez davr", "Тез давр", "Быстрый период"),
        ["Hisobot_TezKecha"] = ("Kecha", "Кеча", "Вчера"),
        ["Hisobot_Tez7Kun"] = ("Oxirgi 7 kun", "Охирги 7 кун", "Последние 7 дней"),
        ["Hisobot_TezShuOy"] = ("Shu oy", "Шу ой", "Этот месяц"),
        ["Hisobot_TezOtganOy"] = ("O'tgan oy", "Ўтган ой", "Прошлый месяц"),
        ["Hisobot_KunlikIzoh"] = ("Kunlik guruhlashda smena ochilgan sanaga yoziladi", "Кунлик гуруҳлашда смена очилган санага ёзилади", "При группировке по дням смена относится к дате открытия"),
        ["Hisobot_Davr"] = ("Davr: {0} dan {1} gacha · {2} ta yopilgan smena", "Давр: {0} дан {1} гача · {2} та ёпилган смена", "Период: с {0} по {1} · закрытых смен: {2}"),
        ["Hisobot_KpiJamiSavdo"] = ("Jami savdo", "Жами савдо", "Всего продаж"),
        ["Hisobot_KpiSomSmena"] = ("so'm · {0} smena", "сўм · {0} смена", "сум · смен: {0}"),
        ["Hisobot_KpiLitr"] = ("Litr", "Литр", "Литры"),
        ["Hisobot_KpiBarchaAparatlar"] = ("barcha aparatlar", "барча аппаратлар", "все аппараты"),
        ["Hisobot_KpiNaqd"] = ("Naqd", "Нақд", "Наличные"),
        ["Hisobot_KpiPlastik"] = ("Plastik", "Пластик", "Пластик"),
        ["Hisobot_KpiDepozit"] = ("Depozit", "Депозит", "Депозит"),
        ["Hisobot_KpiNasiya"] = ("Nasiya", "Насия", "В долг"),
        ["Hisobot_KpiQaytgan"] = ("qaytgan {0}", "қайтган {0}", "возвращено {0}"),
        ["Hisobot_KpiXarajat"] = ("Xarajat", "Харажат", "Расходы"),
        ["Hisobot_KpiXarajatIzoh"] = ("{0} ta smenada", "{0} та сменада", "за смен: {0}"),
        ["Hisobot_KpiKamomat"] = ("Kamomat", "Камомат", "Недостача"),
        ["Hisobot_KpiOrtiqcha"] = ("ortiqcha {0}", "ортиқча {0}", "излишек {0}"),
        ["Hisobot_KpiAvans"] = ("Avans", "Аванс", "Авансы"),
        ["Hisobot_KpiAvansIzoh"] = ("operatorlarga berilgan", "операторларга берилган", "выдано операторам"),
        ["Hisobot_JadvalSarlavha"] = ("Smenalar bo'yicha", "Сменалар бўйича", "По сменам"),
        ["Hisobot_ColSmena"] = ("Smena", "Смена", "Смена"),
        ["Hisobot_ColKun"] = ("Kun", "Кун", "День"),
        ["Hisobot_ColOy"] = ("Oy", "Ой", "Месяц"),
        ["Hisobot_ColOperator"] = ("Operator", "Оператор", "Оператор"),
        ["Hisobot_ColSmenalar"] = ("Smenalar", "Сменалар", "Смены"),
        ["Hisobot_ColLitr"] = ("Litr", "Литр", "Литры"),
        ["Hisobot_ColSavdo"] = ("Savdo", "Савдо", "Продажи"),
        ["Hisobot_ColPlastik"] = ("Plastik", "Пластик", "Пластик"),
        ["Hisobot_ColDepozit"] = ("Depozit", "Депозит", "Депозит"),
        ["Hisobot_ColNasiya"] = ("Nasiya", "Насия", "Долги"),
        ["Hisobot_ColQaytgan"] = ("Qaytgan", "Қайтган", "Возвращено"),
        ["Hisobot_ColXarajat"] = ("Xarajat", "Харажат", "Расходы"),
        ["Hisobot_ColNaqd"] = ("Naqd", "Нақд", "Наличные"),
        ["Hisobot_ColFarq"] = ("Farq", "Фарқ", "Разница"),
        ["Hisobot_ColOrtiqcha"] = ("Ortiqcha", "Ортиқча", "Излишек"),
        ["Hisobot_SmenaSoni"] = ("{0} smena", "{0} смена", "смен: {0}"),
        ["Hisobot_Bosh"] = ("Bu davrda yopilgan smena yo'q", "Бу даврда ёпилган смена йўқ", "За этот период закрытых смен нет"),
        ["Hisobot_BakSarlavha"] = ("Aparatlar va baklar", "Аппаратлар ва баклар", "Аппараты и баки"),
        ["Hisobot_BakFormula"] = ("Bak boshida + kirim − sotildi = bak oxirida, litrda", "Бак бошида + кирим − сотилди = бак охирида, литрда", "Остаток на начало + приход − продано = остаток на конец, в литрах"),
        ["Hisobot_BakOperatorgaBogliqEmas"] = ("Bak jadvali operatorga bog'liq emas — butun shoxobcha bo'yicha ko'rsatiladi.", "Бак жадвали операторга боғлиқ эмас — бутун шохобча бўйича кўрсатилади.", "Таблица баков не зависит от оператора — показана по всей станции."),
        ["Hisobot_ColAparat"] = ("Aparat", "Аппарат", "Аппарат"),
        ["Hisobot_ColYoqilgi"] = ("Yoqilg'i", "Ёқилғи", "Топливо"),
        ["Hisobot_ColBakBoshida"] = ("Bak boshida", "Бак бошида", "Бак на начало"),
        ["Hisobot_ColKirim"] = ("Kirim", "Кирим", "Приход"),
        ["Hisobot_ColSotildi"] = ("Sotildi", "Сотилди", "Продано"),
        ["Hisobot_ColBakOxirida"] = ("Bak oxirida", "Бак охирида", "Бак на конец"),
        ["Nasiyalar_Izoh"] = ("Qarzga yoqilg'i olgan mijozlar va qaytarish muddatlari", "Қарзга ёқилғи олган мижозлар ва қайтариш муддатлари", "Клиенты, взявшие топливо в долг, и сроки возврата"),
        ["Nasiyalar_SmenaKerak"] = ("Nasiya yozish uchun ochiq smena kerak. Smena Savdo bo'limida ochiladi.", "Насия ёзиш учун очиқ смена керак. Смена Савдо бўлимида очилади.", "Для записи долга нужна открытая смена. Смена открывается в разделе «Продажи»."),
        ["Nasiyalar_FaolQarz"] = ("Faol qarz", "Фаол қарз", "Активный долг"),
        ["Nasiyalar_MuddatiOtgan"] = ("Muddati o'tgan", "Муддати ўтган", "Просроченные"),
        ["Nasiyalar_OyBerilgan"] = ("Shu oy berilgan", "Шу ой берилган", "Выдано в этом месяце"),
        ["Nasiyalar_OyQaytgan"] = ("Shu oy qaytgan", "Шу ой қайтган", "Возвращено в этом месяце"),
        ["Nasiyalar_MijozSoni"] = ("{0} ta mijoz", "{0} та мижоз", "Клиентов: {0}"),
        ["Nasiyalar_NasiyaSoni"] = ("{0} ta nasiya", "{0} та насия", "Долгов: {0}"),
        ["Nasiyalar_TolovSoni"] = ("{0} ta to'lov", "{0} та тўлов", "Платежей: {0}"),
        ["Nasiyalar_QidiruvQisqa"] = ("Ism, telefon yoki raqam", "Исм, телефон ёки рақам", "Имя, телефон или номер"),
        ["Nasiyalar_Royxati"] = ("Nasiyalar ro'yxati", "Насиялар рўйхати", "Список долгов"),
        ["Nasiyalar_Filtr"] = ("Filtr", "Филтр", "Фильтр"),
        ["Nasiyalar_Hammasi"] = ("Hammasi", "Ҳаммаси", "Все"),
        ["Nasiyalar_Faol"] = ("Faol", "Фаол", "Активные"),
        ["Nasiyalar_Yopilgan"] = ("Yopilgan", "Ёпилган", "Закрытые"),
        ["Nasiyalar_Mijoz"] = ("Mijoz", "Мижоз", "Клиент"),
        ["Nasiyalar_Mashina"] = ("Mashina", "Машина", "Машина"),
        ["Nasiyalar_Yozilgan"] = ("Yozilgan", "Ёзилган", "Записан"),
        ["Nasiyalar_Qaytdi"] = ("Qaytdi", "Қайтди", "Вернул"),
        ["Nasiyalar_QaytdiAria"] = ("{0} qarzi qaytdi", "{0} қарзи қайтди", "{0} вернул долг"),
        ["Nasiyalar_YopilganSana"] = ("Yopilgan {0}", "Ёпилган {0}", "Закрыт {0}"),
        ["Nasiyalar_Yoq"] = ("Nasiyalar topilmadi", "Насиялар топилмади", "Долги не найдены"),
        ["Nasiyalar_YozilganQisqa"] = ("Yozilgan {0} · #{1} · {2}", "Ёзилган {0} · #{1} · {2}", "Записан {0} · №{1} · {2}"),
        ["Nasiyalar_QaytishlarTarixi"] = ("Qaytishlar", "Қайтишлар", "Возвраты"),
        ["Nasiyalar_SmenadanTashqari"] = ("smenadan tashqari", "сменадан ташқари", "вне смены"),
        ["Nasiyalar_QaytishYoq"] = ("Hali qaytarilmagan", "Ҳали қайтарилмаган", "Пока ничего не возвращено"),
        ["Nasiyalar_QaytishiBorOchirilmaydi"] = ("Qaytishi bor nasiyani o'chirib bo'lmaydi — avval qaytishlarni o'chiring.", "Қайтиши бор насияни ўчириб бўлмайди — аввал қайтишларни ўчиринг.", "Долг с возвратами удалить нельзя — сначала удалите возвраты."),
        ["Nasiyalar_OchirishSavol"] = ("Bu nasiya o'chirilsinmi? Amalni qaytarib bo'lmaydi.", "Бу насия ўчирилсинми? Амални қайтариб бўлмайди.", "Удалить этот долг? Действие необратимо."),
        ["Nasiyalar_QaytishOchirishSavol"] = ("Bu qaytish o'chirilsinmi? Qarz qoldig'i tiklanadi.", "Бу қайтиш ўчирилсинми? Қарз қолдиғи тикланади.", "Удалить этот возврат? Остаток долга восстановится."),
        ["Nasiyalar_HaOchirish"] = ("Ha, o'chirish", "Ҳа, ўчириш", "Да, удалить"),
        ["Nasiyalar_Ochirish"] = ("Nasiyani o'chirish", "Насияни ўчириш", "Удалить долг"),
        ["Nasiyalar_Ochirildi"] = ("O'chirildi", "Ўчирилди", "Удалено"),
        ["Savdo_SmenaOchiq"] = ("Smena ochiq", "Смена очиқ", "Смена открыта"),
        ["Savdo_SmenaYopiq"] = ("Smena yopiq", "Смена ёпиқ", "Смена закрыта"),
        ["Savdo_Dan"] = ("dan", "дан", "с"),
        ["Savdo_SmenaniYopish"] = ("Smenani yopish", "Сменани ёпиш", "Закрыть смену"),
        ["Savdo_OchilgandagiQoldiqlar"] = ("Smena ochilgandagi qoldiqlar", "Смена очилгандаги қолдиқлар", "Остатки при открытии смены"),
        ["Savdo_OperatorKiritgan"] = ("Operator ochishda o'zi kiritgan", "Оператор очишда ўзи киритган", "Введено оператором при открытии"),
        ["Savdo_QaytimNaqd"] = ("Qaytim puli · naqd", "Қайтим пули · нақд", "Сдача · наличные"),
        ["Savdo_TerminalPlastik"] = ("Terminal · plastik", "Терминал · пластик", "Терминал · пластик"),
        ["Savdo_TerminalIzoh"] = ("00:00 dan keyingi savdo", "00:00 дан кейинги савдо", "Продажи после 00:00"),
        ["Savdo_DepozitKarta"] = ("Depozit karta", "Депозит карта", "Депозитная карта"),
        ["Savdo_DepozitIzoh"] = ("Zapravka bank kartasi", "Заправка банк картаси", "Банковская карта заправки"),
        ["Savdo_Bosqichlar"] = ("Smena bosqichlari", "Смена босқичлари", "Этапы смены"),
        ["Savdo_Bosqich1"] = ("Smena ochildi", "Смена очилди", "Смена открыта"),
        ["Savdo_Bosqich1Izoh"] = ("{0} · uchta qoldiq yozildi", "{0} · учта қолдиқ ёзилди", "{0} · записаны три остатка"),
        ["Savdo_Bosqich2"] = ("Kun davomida", "Кун давомида", "В течение дня"),
        ["Savdo_Bosqich2Izoh"] = ("nasiya, qaytgan qarz, xarajat", "насия, қайтган қарз, харажат", "долги, возвраты, расходы"),
        ["Savdo_Bosqich3"] = ("Smena oxirida", "Смена охирида", "В конце смены"),
        ["Savdo_Bosqich3Izoh"] = ("pult, terminal, depozit, naqd", "пулт, терминал, депозит, нақд", "пульт, терминал, депозит, наличные"),
        ["Savdo_JoriySmena"] = ("Joriy smena #{0}", "Жорий смена #{0}", "Текущая смена №{0}"),
        ["Savdo_Operator"] = ("Operator", "Оператор", "Оператор"),
        ["Savdo_Ochildi"] = ("Ochildi", "Очилди", "Открыта"),
        ["Savdo_Davomiyligi"] = ("Davomiyligi", "Давомийлиги", "Длительность"),
        ["Savdo_NasiyaBerildi"] = ("Nasiya berildi", "Насия берилди", "Выдано в долг"),
        ["Savdo_QaytganNasiya"] = ("Qaytgan nasiya", "Қайтган насия", "Возвращено долгов"),
        ["Savdo_Xarajatlar"] = ("Xarajatlar", "Харажатлар", "Расходы"),
        ["Savdo_FarqIzoh"] = ("Savdo va kassadagi farq smena yopilganda pult ko'rsatkichlaridan hisoblanadi.", "Савдо ва кассадаги фарқ смена ёпилганда пулт кўрсаткичларидан ҳисобланади.", "Продажи и разница в кассе считаются при закрытии смены по показаниям пультов."),
        ["Savdo_Aparatlar"] = ("Aparatlar", "Аппаратлар", "Аппараты"),
        ["Savdo_AparatlarIzoh"] = ("Pult ko'rsatkichi va bak qoldig'i oxirgi yopilgan smena holatida, {0}", "Пулт кўрсаткичи ва бак қолдиғи охирги ёпилган смена ҳолатида, {0}", "Показание пульта и остаток бака на момент последней закрытой смены, {0}"),
        ["Savdo_SomLitr"] = ("so'm / litr", "сўм / литр", "сум / литр"),
        ["Savdo_PultKorsatkichi"] = ("Pult ko'rsatkichi", "Пулт кўрсаткичи", "Показание пульта"),
        ["Savdo_BakQoldigi"] = ("Bak qoldig'i", "Бак қолдиғи", "Остаток бака"),
        ["Savdo_Nasiya"] = ("Nasiya", "Насия", "Долги"),
        ["Savdo_NasiyaShuSmenada"] = ("Shu smenada {0} ta · {1} so'm", "Шу сменада {0} та · {1} сўм", "В этой смене: {0} · {1} сум"),
        ["Savdo_MuddatGacha"] = ("{0} gacha", "{0} гача", "до {0}"),
        ["Savdo_NasiyaYoq"] = ("Bu smenada nasiya yo'q", "Бу сменада насия йўқ", "В этой смене долгов нет"),
        ["Savdo_QarzniQaytardi"] = ("qarzini qaytardi", "қарзини қайтарди", "вернул долг"),
        ["Savdo_XarajatIzoh"] = ("Boshliq aytgan to'lovlar · shu smenada {0} ta", "Бошлиқ айтган тўловлар · шу сменада {0} та", "Платежи по указанию начальника · в этой смене: {0}"),
        ["Savdo_Kassadan"] = ("kassadan", "кассадан", "из кассы"),
        ["Savdo_DepozitKartadan"] = ("depozit kartadan", "депозит картадан", "с депозитной карты"),
        ["Savdo_XarajatYoq"] = ("Bu smenada xarajat yo'q", "Бу сменада харажат йўқ", "В этой смене расходов нет"),
        ["Savdo_Jami"] = ("Jami", "Жами", "Итого"),
        ["Savdo_MuddatiOtganQarzlar"] = ("Muddati o'tgan qarzlar", "Муддати ўтган қарзлар", "Просроченные долги"),
        ["Savdo_MijozSumma"] = ("{0} ta mijoz · {1} so'm", "{0} та мижоз · {1} сўм", "Клиентов: {0} · {1} сум"),
        ["Savdo_MuddatEdi"] = ("muddat {0} edi", "муддат {0} эди", "срок был {0}"),
        ["Savdo_BarchaNasiyalar"] = ("Barcha nasiyalar", "Барча насиялар", "Все долги"),
        ["Savdo_OxirgiSmenaYopdi"] = ("Oxirgi smena #{0} ni {1} yopdi", "Охирги смена #{0} ни {1} ёпди", "Последнюю смену №{0} закрыл(а) {1}"),
        ["Savdo_SmenaniOchish"] = ("Smenani ochish", "Сменани очиш", "Открыть смену"),
        ["Savdo_OchishIzoh"] = ("Uchta qoldiqni hozirgi holat bo'yicha yozing. Ular oldingi smenadan avtomatik olinmaydi.", "Учта қолдиқни ҳозирги ҳолат бўйича ёзинг. Улар олдинги сменадан автоматик олинмайди.", "Введите три остатка по текущему состоянию. Из предыдущей смены они не переносятся автоматически."),
        ["Savdo_QaytimPuli"] = ("Kassadagi qaytim puli", "Кассадаги қайтим пули", "Сдача в кассе"),
        ["Savdo_QaytimIzoh"] = ("Oldingi smena qaytim uchun qoldirgan naqd", "Олдинги смена қайтим учун қолдирган нақд", "Наличные, оставленные прошлой сменой для сдачи"),
        ["Savdo_TerminalSumma"] = ("Terminaldagi summa · plastik", "Терминалдаги сумма · пластик", "Сумма на терминале · пластик"),
        ["Savdo_TerminalSummaIzoh"] = ("Terminal 00:00 da nollanadi. Ekranda hozir ko'rsatayotgan summani yozing.", "Терминал 00:00 да нолланади. Экранда ҳозир кўрсатаётган суммани ёзинг.", "Терминал обнуляется в 00:00. Введите сумму, которую он показывает сейчас."),
        ["Savdo_DepozitQoldigi"] = ("Depozit karta qoldig'i", "Депозит карта қолдиғи", "Остаток депозитной карты"),
        ["Savdo_DepozitQoldigiIzoh"] = ("Zapravka bank kartasidagi hozirgi qoldiq", "Заправка банк картасидаги ҳозирги қолдиқ", "Текущий остаток на банковской карте заправки"),
        ["Savdo_OchishVaqti"] = ("{0} · ochilish vaqti {1}", "{0} · очилиш вақти {1}", "{0} · время открытия {1}"),
        ["Savdo_OchishRuxsatYoq"] = ("Smena yopiq. Smenani ochish uchun ruxsat kerak — boshliqqa murojaat qiling.", "Смена ёпиқ. Сменани очиш учун рухсат керак — бошлиққа мурожаат қилинг.", "Смена закрыта. Для открытия нужно разрешение — обратитесь к начальнику."),
        ["Savdo_OxirgiSmena"] = ("Oxirgi smena #{0}", "Охирги смена #{0}", "Последняя смена №{0}"),
        ["Savdo_Yopilgan"] = ("Yopilgan", "Ёпилган", "Закрыта"),
        ["Savdo_Soat"] = ("{0} soat", "{0} соат", "{0} ч"),
        ["Savdo_SavdoQator"] = ("Savdo", "Савдо", "Продажи"),
        ["Savdo_SotilganLitr"] = ("Sotilgan litr", "Сотилган литр", "Продано литров"),
        ["Savdo_Plastik"] = ("Plastik", "Пластик", "Пластик"),
        ["Savdo_DepozitFarqi"] = ("Depozit farqi", "Депозит фарқи", "Разница депозита"),
        ["Savdo_Kamomat"] = ("Kamomat", "Камомат", "Недостача"),
        ["Savdo_OylikdanAyirildi"] = ("{0} oyligidan ayirildi", "{0} ойлигидан айирилди", "вычтено из зарплаты: {0}"),
        ["Savdo_Ortiqcha"] = ("Ortiqcha", "Ортиқча", "Излишек"),
        ["Savdo_HisobigaYozildi"] = ("{0} hisobiga yozildi", "{0} ҳисобига ёзилди", "записано на счёт: {0}"),
        ["Savdo_FarqYoq"] = ("Farq yo'q, kassa to'g'ri", "Фарқ йўқ, касса тўғри", "Разницы нет, касса верна"),
        ["Savdo_AparatlarHolati"] = ("Aparatlar holati", "Аппаратлар ҳолати", "Состояние аппаратов"),
        ["Savdo_SmenaYopilgandanKeyin"] = ("Smena #{0} yopilgandan keyin", "Смена #{0} ёпилгандан кейин", "После закрытия смены №{0}"),
        ["Savdo_HozirgiHolat"] = ("Hozirgi holat", "Ҳозирги ҳолат", "Текущее состояние"),
        ["Savdo_Aparat"] = ("Aparat", "Аппарат", "Аппарат"),
        ["Savdo_Pult"] = ("Pult, L", "Пулт, Л", "Пульт, л"),
        ["Savdo_Bak"] = ("Bak, L", "Бак, Л", "Бак, л"),
        ["Savdo_SoatDaqiqa"] = ("{0} soat {1} daqiqa", "{0} соат {1} дақиқа", "{0} ч {1} мин"),
        ["Savdo_OchirishTasdiq"] = ("O'chirishni tasdiqlaysizmi? {0}", "Ўчиришни тасдиқлайсизми? {0}", "Подтвердить удаление? {0}"),
        ["Savdo_SmenaOchildi"] = ("Smena ochildi", "Смена очилди", "Смена открыта"),
        ["Yopish_Sarlavha"] = ("Smenani yopish", "Сменани ёпиш", "Закрытие смены"),
        ["Yopish_SmenaN"] = ("Smena #{0}", "Смена #{0}", "Смена №{0}"),
        ["Yopish_SavdogaQaytish"] = ("Savdoga qaytish", "Савдога қайтиш", "Назад к продажам"),
        ["Yopish_AparatKorsatkichlari"] = ("Aparat ko'rsatkichlari", "Аппарат кўрсаткичлари", "Показания аппаратов"),
        ["Yopish_AparatIzoh"] = ("Har bir pultdagi \"Total, L\" qiymatini yozing. Sotilgan litr va summa o'zi chiqadi.", "Ҳар бир пултдаги \"Тотал, Л\" қийматини ёзинг. Сотилган литр ва сумма ўзи чиқади.", "Введите «Total, л» с каждого пульта. Проданные литры и сумма посчитаются сами."),
        ["Yopish_Aparat"] = ("Aparat", "Аппарат", "Аппарат"),
        ["Yopish_Oldingi"] = ("Oldingi, L", "Олдинги, Л", "Прежнее, л"),
        ["Yopish_Yangi"] = ("Yangi, L", "Янги, Л", "Новое, л"),
        ["Yopish_Sotilgan"] = ("Sotilgan", "Сотилган", "Продано"),
        ["Yopish_Narx"] = ("Narx", "Нарх", "Цена"),
        ["Yopish_Summa"] = ("Summa", "Сумма", "Сумма"),
        ["Yopish_Jami"] = ("Jami", "Жами", "Итого"),
        ["Yopish_EskiNarxda"] = ("{0}: narx o'zgargunicha {1} L × {2} = {3}", "{0}: нарх ўзгаргунича {1} Л × {2} = {3}", "{0}: до смены цены {1} л × {2} = {3}"),
        ["Yopish_OldingidanKichik"] = ("Oldingi ko'rsatkich {0} dan kichik bo'lishi mumkin emas", "Олдинги кўрсаткич {0} дан кичик бўлиши мумкин эмас", "Не может быть меньше прежнего показания {0}"),
        ["Yopish_PlastikDepozit"] = ("Plastik va depozit", "Пластик ва депозит", "Пластик и депозит"),
        ["Yopish_PlastikTerminal"] = ("Plastik · terminal", "Пластик · терминал", "Пластик · терминал"),
        ["Yopish_TerminalSummasi"] = ("Yopishdagi terminal summasi", "Ёпишдаги терминал суммаси", "Сумма терминала при закрытии"),
        ["Yopish_TerminalIzoh"] = ("Tungi nollash chekidagi summa va nollashdan keyingi savdoni qo'shib, bitta raqam yozing.", "Тунги ноллаш чекидаги сумма ва ноллашдан кейинги савдони қўшиб, битта рақам ёзинг.", "Сложите сумму из ночного чека обнуления и продажи после него — введите одно число."),
        ["Yopish_OchishdaYozilgan"] = ("Ochishda yozilgan", "Очишда ёзилган", "Записано при открытии"),
        ["Yopish_ShuSmenaPlastik"] = ("Shu smena plastik", "Шу смена пластик", "Пластик за смену"),
        ["Yopish_PlastikKam"] = ("Ochishdagidan kam chiqdi. Tungi chek summasini qo'shganingizni tekshiring.", "Очишдагидан кам чиқди. Тунги чек суммасини қўшганингизни текширинг.", "Получилось меньше, чем при открытии. Проверьте, добавили ли сумму ночного чека."),
        ["Yopish_DepozitKarta"] = ("Depozit karta", "Депозит карта", "Депозитная карта"),
        ["Yopish_KartadagiQoldiq"] = ("Kartadagi hozirgi qoldiq", "Картадаги ҳозирги қолдиқ", "Текущий остаток на карте"),
        ["Yopish_DepozitIzoh"] = ("Zapravkaning umumiy bank kartasidagi qoldiq. Ilova orqali tashlangan pullar shu yerga tushadi.", "Заправканинг умумий банк картасидаги қолдиқ. Илова орқали ташланган пуллар шу ерга тушади.", "Остаток на общей банковской карте заправки. Сюда попадают деньги, переведённые через приложение."),
        ["Yopish_DepozitFarqi"] = ("Depozit farqi", "Депозит фарқи", "Разница депозита"),
        ["Yopish_DepozitManfiy"] = ("Kartadan pul yechilgan. Tekshiruvda naqd savdo terminal orqali o'tkazilgan bo'lsa, bu kamomat emas.", "Картадан пул ечилган. Текширувда нақд савдо терминал орқали ўтказилган бўлса, бу камомат эмас.", "С карты списаны деньги. Если при проверке наличные продажи проведены через терминал — это не недостача."),
        ["Yopish_Yozuvlar"] = ("Shu smenadagi yozuvlar", "Шу сменадаги ёзувлар", "Записи этой смены"),
        ["Yopish_YozuvlarIzoh"] = ("Yopishdan oldin yetishmaganini qo'shib qo'ying", "Ёпишдан олдин етишмаганини қўшиб қўйинг", "Перед закрытием добавьте недостающее"),
        ["Yopish_NasiyaBerildi"] = ("Nasiya berildi", "Насия берилди", "Выдано в долг"),
        ["Yopish_QaytganNasiya"] = ("Qaytgan nasiya", "Қайтган насия", "Возвращённые долги"),
        ["Yopish_Xarajatlar"] = ("Xarajatlar", "Харажатлар", "Расходы"),
        ["Yopish_Ta"] = ("{0} ta", "{0} та", "{0} шт."),
        ["Yopish_KassadagiNaqd"] = ("Kassadagi naqd", "Кассадаги нақд", "Наличные в кассе"),
        ["Yopish_QaytimOchishda"] = ("Qaytim puli, ochishda", "Қайтим пули, очишда", "Сдача при открытии"),
        ["Yopish_SavdoAparatlar"] = ("Savdo, aparatlar", "Савдо, аппаратлар", "Продажи по аппаратам"),
        ["Yopish_Plastik"] = ("Plastik", "Пластик", "Пластик"),
        ["Yopish_Nasiya"] = ("Nasiya", "Насия", "Долги"),
        ["Yopish_KassadaBolishiKerak"] = ("Kassada bo'lishi kerak", "Кассада бўлиши керак", "Должно быть в кассе"),
        ["Yopish_SanalganNaqd"] = ("Sanalgan naqd", "Саналган нақд", "Пересчитанные наличные"),
        ["Yopish_OylikdanAyiriladi"] = ("{0} oyligidan ayiriladi", "{0} ойлигидан айирилади", "Будет вычтено из зарплаты: {0}"),
        ["Yopish_OrtiqchaYoziladi"] = ("Operator hisobiga ortiqcha bo'lib yoziladi", "Оператор ҳисобига ортиқча бўлиб ёзилади", "Запишется оператору как излишек"),
        ["Yopish_NaqdniSanang"] = ("Kassadagi naqdni sanab, yuqoriga yozing.", "Кассадаги нақдни санаб, юқорига ёзинг.", "Пересчитайте наличные в кассе и введите выше."),
        ["Yopish_ToliqEmas"] = ("Hisob chiqishi uchun barcha aparat ko'rsatkichlarini, plastik va depozitni to'g'ri kiriting.", "Ҳисоб чиқиши учун барча аппарат кўрсаткичларини, пластик ва депозитни тўғри киритинг.", "Для расчёта введите показания всех аппаратов, пластик и депозит."),
        ["Yopish_Izoh"] = ("Izoh, ixtiyoriy", "Изоҳ, ихтиёрий", "Комментарий (необязательно)"),
        ["Yopish_IzohPlaceholder"] = ("Masalan: 50 000 lik kupyura yirtiq", "Масалан: 50 000 лик купюра йиртиқ", "Например: порвана купюра 50 000"),
        ["Yopish_YopilgachIzoh"] = ("Yopilgach pult ko'rsatkichlari yangilanadi, har bir bak qoldig'idan sotilgan litr ayiriladi, farq operator hisobiga yoziladi.", "Ёпилгач пулт кўрсаткичлари янгиланади, ҳар бир бак қолдиғидан сотилган литр айирилади, фарқ оператор ҳисобига ёзилади.", "После закрытия показания пультов обновятся, из остатка каждого бака вычтутся проданные литры, разница запишется на счёт оператора."),
        ["Yopish_TasdiqSarlavha"] = ("Smenani yopasizmi?", "Сменани ёпасизми?", "Закрыть смену?"),
        ["Yopish_Farq"] = ("Farq", "Фарқ", "Разница"),
        ["Yopish_Tasdiqlash"] = ("Ha, yopish", "Ҳа, ёпиш", "Да, закрыть"),
        ["Yopish_Yopildi"] = ("Smena yopildi", "Смена ёпилди", "Смена закрыта"),
        ["Raqam"] = ("Raqam", "Рақам", "Номер"),
        ["Sozlama_Bolimlari"] = ("Sozlamalar bo'limlari", "Созламалар бўлимлари", "Разделы настроек"),
        ["Sozlama_AparatIzoh"] = ("Har bir aparatning o'z pulti va o'z baki bor", "Ҳар бир апаратнинг ўз пулти ва ўз баки бор", "У каждой колонки свой пульт и свой бак"),
        ["Sozlama_Bolimlar"] = ("Bo'limlar", "Бўлимлар", "Разделы"),
        ["Sozlama_Amallar"] = ("Amallar", "Амаллар", "Действия"),
        ["Sozlama_RolBoyichaTiklash"] = ("Rol bo'yicha tiklash", "Рол бўйича тиклаш", "Сбросить по роли"),
        ["Sozlama_RuxsatSoni"] = ("{0} ta ruxsat", "{0} та рухсат", "Разрешений: {0}"),
        ["Sozlama_RuxsatlarniSaqlash"] = ("Ruxsatlarni saqlash", "Рухсатларни сақлаш", "Сохранить разрешения"),
        ["Sozlama_Saqlanmagan"] = ("Saqlanmagan o'zgarishlar", "Сақланмаган ўзгаришлар", "Несохранённые изменения"),
        ["Sozlama_RuxsatEslatma"] = ("Olib tashlandi: Sotuv kiritish, Sotuvni tahrirlash, Sotuvni bekor qilish. Ularning o'rnini smena yopish va ko'rsatkichni tuzatish egalladi.", "Олиб ташланди: Сотув киритиш, Сотувни таҳрирлаш, Сотувни бекор қилиш. Уларнинг ўрнини смена ёпиш ва кўрсаткични тузатиш эгаллади.", "Удалено: ввод продаж, редактирование и отмена продаж. Их заменили закрытие смены и исправление показаний."),
        ["Ruxsat_Boshqaruv"] = ("Boshqaruv", "Бошқарув", "Управление"),
        ["Ruxsat_Savdo"] = ("Savdo", "Савдо", "Продажи"),
        ["Ruxsat_Smenalar"] = ("Smenalar", "Сменалар", "Смены"),
        ["Ruxsat_Nasiyalar"] = ("Nasiyalar", "Насиялар", "Долги"),
        ["Ruxsat_Hisobotlar"] = ("Hisobotlar", "Ҳисоботлар", "Отчёты"),
        ["Ruxsat_Operatorlar"] = ("Operatorlar", "Операторлар", "Операторы"),
        ["Ruxsat_Audit"] = ("Audit", "Аудит", "Аудит"),
        ["Ruxsat_Sozlamalar"] = ("Sozlamalar", "Созламалар", "Настройки"),
        ["Ruxsat_SmenaOchish"] = ("Smena ochish", "Смена очиш", "Открытие смены"),
        ["Ruxsat_SmenaOchish_Izoh"] = ("Uchta boshlang'ich qoldiqni kiritib smena ochadi", "Учта бошлангъич қолдиқни киритиб смена очади", "Открывает смену, вводя три начальных остатка"),
        ["Ruxsat_SmenaYopish"] = ("Smena yopish", "Смена ёпиш", "Закрытие смены"),
        ["Ruxsat_SmenaYopish_Izoh"] = ("Pult ko'rsatkichlari, plastik, depozit va naqdni kiritib yopadi", "Пулт кўрсаткичлари, пластик, депозит ва нақдни киритиб ёпади", "Закрывает смену, вводя показания пультов, пластик, депозит и наличные"),
        ["Ruxsat_NasiyaYozish"] = ("Nasiya yozish", "Насия ёзиш", "Запись долга"),
        ["Ruxsat_NasiyaYozish_Izoh"] = ("Qarzga yoqilg'i berilganini yozadi", "Қарзга ёқилғи берилганини ёзади", "Записывает топливо, выданное в долг"),
        ["Ruxsat_QarzQaytdi"] = ("Qarz qaytdi", "Қарз қайтди", "Возврат долга"),
        ["Ruxsat_QarzQaytdi_Izoh"] = ("Qaytgan qarzni to'liq yoki qisman yopadi", "Қайтган қарзни тўлиқ ёки қисман ёпади", "Полностью или частично закрывает возвращённый долг"),
        ["Ruxsat_XarajatYozish"] = ("Xarajat yozish", "Харажат ёзиш", "Запись расхода"),
        ["Ruxsat_XarajatYozish_Izoh"] = ("Boshliq aytgan to'lovlarni yozadi", "Бошлиқ айтган тўловларни ёзади", "Записывает платежи по указанию начальника"),
        ["Ruxsat_BakKirim"] = ("Bakka kirim", "Бакка кирим", "Приход в бак"),
        ["Ruxsat_BakKirim_Izoh"] = ("Zavoddan kelgan yoqilg'ini bakka qo'shadi", "Заводдан келган ёқилғини бакка қўшади", "Добавляет в бак топливо с завода"),
        ["Ruxsat_KorsatkichTuzatish"] = ("Ko'rsatkichni tuzatish", "Кўрсаткични тузатиш", "Исправление показаний"),
        ["Ruxsat_KorsatkichTuzatish_Izoh"] = ("Yopilgan smenadagi xato ko'rsatkichni sabab bilan tuzatadi", "Ёпилган сменадаги хато кўрсаткични сабаб билан тузатади", "Исправляет ошибочное показание закрытой смены с указанием причины"),
        ["Ruxsat_AvansBerish"] = ("Avans berish", "Аванс бериш", "Выдача аванса"),
        ["Ruxsat_AvansBerish_Izoh"] = ("Operatorga avans yoki maosh to'lovini yozadi", "Операторга аванс ёки маош тўловини ёзади", "Записывает оператору аванс или выплату зарплаты"),
        ["Ruxsat_Eksport"] = ("Eksport", "Экспорт", "Экспорт"),
        ["Ruxsat_Eksport_Izoh"] = ("Hisobotlarni Excel faylga chiqaradi", "Ҳисоботларни Excel файлга чиқаради", "Выгружает отчёты в файл Excel"),
        ["Aparat_PultKorsatkichi"] = ("Pult ko'rsatkichi", "Пулт кўрсаткичи", "Показание пульта"),
        ["Aparat_BakQoldigi"] = ("Bak qoldig'i", "Бак қолдиғи", "Остаток бака"),
        ["Aparat_Tahrirlash"] = ("{0}-aparatni tahrirlash", "{0}-апаратни таҳрирлаш", "Редактирование колонки {0}"),
        ["Aparat_AuditgaYoziladi"] = ("O'zgarishlar auditga yoziladi", "Ўзгаришлар аудитга ёзилади", "Изменения записываются в аудит"),
        ["Aparat_YangiIzoh"] = ("Boshlang'ich pult ko'rsatkichi va bak qoldig'i yoziladi", "Бошлангъич пулт кўрсаткичи ва бак қолдиғи ёзилади", "Укажите начальное показание пульта и остаток бака"),
        ["Aparat_PultLitr"] = ("Pult ko'rsatkichi, L", "Пулт кўрсаткичи, Л", "Показание пульта, л"),
        ["Aparat_BoshlangichPult"] = ("Boshlang'ich pult ko'rsatkichi, L", "Бошлангъич пулт кўрсаткичи, Л", "Начальное показание пульта, л"),
        ["Aparat_PultIzoh"] = ("Odatda smena yopilganda o'zi yangilanadi. Pult almashtirilsa yoki ta'mirlansa, qo'lda tuzatiladi.", "Одатда смена ёпилганда ўзи янгиланади. Пулт алмаштирилса ёки таъмирланса, қўлда тузатилади.", "Обычно обновляется при закрытии смены. Если пульт заменён или отремонтирован — правится вручную."),
        ["Aparat_BakLitr"] = ("Bak qoldig'i, L", "Бак қолдиғи, Л", "Остаток бака, л"),
        ["Aparat_BoshlangichBak"] = ("Boshlang'ich bak qoldig'i, L", "Бошлангъич бак қолдиғи, Л", "Начальный остаток бака, л"),
        ["Aparat_BakIzoh"] = ("Yangi aparatda boshlang'ich qoldiq yoziladi. Keyin kirim qo'shadi, smena yopilishi ayiradi. Qo'lda faqat o'lchov bo'yicha tuzatiladi.", "Янги апаратда бошлангъич қолдиқ ёзилади. Кейин кирим қўшади, смена ёпилиши айиради. Қўлда фақат ўлчов бўйича тузатилади.", "У новой колонки вводится начальный остаток. Затем приход добавляет, закрытие смены вычитает. Вручную правится только по замеру."),
        ["Aparat_TuzatishSababi"] = ("Tuzatish sababi", "Тузатиш сабаби", "Причина исправления"),
        ["Aparat_SababPlaceholder"] = ("Masalan: metrshtok bilan o'lchandi", "Масалан: метршток билан ўлчанди", "Например: измерено метрштоком"),
        ["Aparat_XatoPult"] = ("Pult ko'rsatkichini to'g'ri yozing", "Пулт кўрсаткичини тўғри ёзинг", "Укажите корректное показание пульта"),
        ["Aparat_XatoBakManfiy"] = ("Bak qoldig'ini qo'lda manfiy qilib bo'lmaydi", "Бак қолдиғини қўлда манфий қилиб бўлмайди", "Остаток бака нельзя вручную сделать отрицательным"),
        ["Aparat_XatoRaqamBand"] = ("Bu raqamli aparat allaqachon bor", "Бу рақамли апарат аллақачон бор", "Колонка с таким номером уже есть"),
        ["Aparat_XatoSabab"] = ("Pult yoki bak qoldig'i o'zgargani uchun tuzatish sababini yozing", "Пулт ёки бак қолдиғи ўзгаргани учун тузатиш сабабини ёзинг", "Показание или остаток изменены — укажите причину исправления"),
        ["Narx_Ozgartirish"] = ("Narxni o'zgartirish", "Нархни ўзгартириш", "Изменить цену"),
        ["Narx_Izoh"] = ("Ochiq smenada narx o'zgarsa, aparatlarning hozirgi pult ko'rsatkichi so'raladi: shu paytgacha sotilgan litr eski narxda hisoblanadi.", "Очиқ сменада нарх ўзгарса, апаратларнинг ҳозирги пулт кўрсаткичи сўралади: шу пайтгача сотилган литр эски нархда ҳисобланади.", "Если цена меняется при открытой смене, запрашиваются текущие показания пультов колонок: литры, проданные до этого момента, считаются по старой цене."),
        ["Narx_TahrirIzoh"] = ("Narxni o'zgartirish uchun ro'yxatdagi \"Narxni o'zgartirish\" tugmasidan foydalaning.", "Нархни ўзгартириш учун рўйхатдаги \"Нархни ўзгартириш\" тугмасидан фойдаланинг.", "Чтобы изменить цену, используйте кнопку «Изменить цену» в списке."),
        ["Narx_Sarlavha"] = ("Narxni o'zgartirish", "Нархни ўзгартириш", "Изменение цены"),
        ["Narx_Kontekst"] = ("Sozlamalar · Yoqilg'i narxlari · {0}", "Созламалар · Ёқилғи нархлари · {0}", "Настройки · Цены на топливо · {0}"),
        ["Narx_Hozirgi"] = ("Hozirgi narx", "Ҳозирги нарх", "Текущая цена"),
        ["Narx_YangiNarx"] = ("Yangi narx, so'm", "Янги нарх, сўм", "Новая цена, сум"),
        ["Narx_SmenaOchiq"] = ("Smena #{0} ochiq", "Смена #{0} очиқ", "Смена №{0} открыта"),
        ["Narx_SmenaOchiqIzoh"] = ("Narx o'zgarguncha sotilgan litr eski narxda hisoblanishi uchun {0} aparatlarining hozirgi pult ko'rsatkichini yozing.", "Нарх ўзгаргунча сотилган литр эски нархда ҳисобланиши учун {0} апаратларининг ҳозирги пулт кўрсаткичини ёзинг.", "Чтобы литры, проданные до смены цены, считались по старой цене, укажите текущее показание пультов колонок {0}."),
        ["Narx_SmenaYopiqIzoh"] = ("Smena ochiq emas — yangi narx darhol kuchga kiradi.", "Смена очиқ эмас — янги нарх дарҳол кучга киради.", "Смена не открыта — новая цена вступит в силу сразу."),
        ["Narx_SmenaBoshida"] = ("Smena boshida", "Смена бошида", "В начале смены"),
        ["Narx_OxirgiQayd"] = ("Oxirgi qayd", "Охирги қайд", "Последняя запись"),
        ["Narx_KorsatkichLabel"] = ("{0}, hozirgi pult ko'rsatkichi", "{0}, ҳозирги пулт кўрсаткичи", "{0}, текущее показание пульта"),
        ["Narx_KorsatkichniYozing"] = ("Hozirgi ko'rsatkichni yozing", "Ҳозирги кўрсаткични ёзинг", "Укажите текущее показание"),
        ["Narx_SmenaBoshidanKichik"] = ("Smena boshidagidan kichik bo'lishi mumkin emas", "Смена бошидагидан кичик бўлиши мумкин эмас", "Не может быть меньше показания на начало смены"),
        ["Narx_OxirgidanKichik"] = ("Oxirgi qayd etilgan ko'rsatkichdan kichik bo'lishi mumkin emas", "Охирги қайд этилган кўрсаткичдан кичик бўлиши мумкин эмас", "Не может быть меньше последнего записанного показания"),
        ["Narx_Sotilgan"] = ("Sotilgan {0} L × {1} = {2} so'm", "Сотилган {0} Л × {1} = {2} сўм", "Продано {0} л × {1} = {2} сум"),
        ["Narx_AparatYoq"] = ("Bu yoqilg'iga aparat biriktirilmagan", "Бу ёқилғига апарат бириктирилмаган", "К этому топливу не привязано ни одной колонки"),
        ["Narx_EskiNarxdaSotilgan"] = ("Eski narxda sotilgan", "Эски нархда сотилган", "Продано по старой цене"),
        ["Narx_JamiLitr"] = ("{0} L, narx {1}", "{0} Л, нарх {1}", "{0} л, цена {1}"),
        ["Narx_KorsatkichlarniTogri"] = ("Barcha ko'rsatkichlarni to'g'ri yozing", "Барча кўрсаткичларни тўғри ёзинг", "Верно укажите все показания"),
        ["Narx_IkkiQism"] = ("Smena yopilganda bu aparatlar ikki qismda hisoblanadi: shu paytgacha {0} dan, keyin yangi narxdan.", "Смена ёпилганда бу апаратлар икки қисмда ҳисобланади: шу пайтгача {0} дан, кейин янги нархдан.", "При закрытии смены эти колонки считаются в две части: до этого момента по {0}, затем по новой цене."),
        ["Narx_Saqlash"] = ("Narxni saqlash", "Нархни сақлаш", "Сохранить цену"),
        ["Operator_Izoh"] = ("Oylik maosh, avans, kamomat va ortiqcha. Kamomat smena yopilganda avtomatik yoziladi.", "Ойлик маош, аванс, камомат ва ортиқча. Камомат смена ёпилганда автоматик ёзилади.", "Месячная зарплата, авансы, недостача и излишек. Недостача записывается автоматически при закрытии смены."),
        ["Operator_Maosh"] = ("Maosh {0}", "Маош {0}", "Зарплата {0}"),
        ["Operator_Smenada"] = ("Smenada", "Сменада", "На смене"),
        ["Operator_OyKorsatkichlari"] = ("{0} ko'rsatkichlari", "{0} кўрсаткичлари", "Показатели: {0}"),
        ["Operator_OldingiOy"] = ("Oldingi oy", "Олдинги ой", "Предыдущий месяц"),
        ["Operator_KeyingiOy"] = ("Keyingi oy", "Кейинги ой", "Следующий месяц"),
        ["Operator_AvansTolov"] = ("Avans / to'lov", "Аванс / тўлов", "Аванс / выплата"),
        ["Operator_YopilganOchiq"] = ("{0} yopilgan, {1} ochiq", "{0} ёпилган, {1} очиқ", "{0} закрыто, {1} открыто"),
        ["Operator_YopilganSmenalarda"] = ("yopilgan smenalarda", "ёпилган сменаларда", "по закрытым сменам"),
        ["Operator_Marta"] = ("{0} marta", "{0} марта", "{0} раз"),
        ["Operator_SmenaRaqami"] = ("smena {0}", "смена {0}", "смена {0}"),
        ["Operator_ShuOy"] = ("shu oy", "шу ой", "за этот месяц"),
        ["Operator_HisobHarakatlari"] = ("Hisob harakatlari", "Ҳисоб ҳаракатлари", "Движения по счёту"),
        ["Operator_SummaSom"] = ("Summa, so'm", "Сумма, сўм", "Сумма, сум"),
        ["Operator_IzohPlaceholder"] = ("Masalan: naqd berildi", "Масалан: нақд берилди", "Например: выдано наличными"),
        ["Operator_AvansIzoh"] = ("Avans va to'lov operatorning joriy qoldig'idan ayiriladi va auditga yoziladi.", "Аванс ва тўлов операторнинг жорий қолдиғидан айирилади ва аудитга ёзилади.", "Аванс и выплата вычитаются из текущего остатка оператора и записываются в аудит."),
        ["Audit_Izoh"] = ("Barcha o'zgartiruvchi amallar. Yangi turlar: nasiya, qarz qaytdi, xarajat, bakka kirim, ko'rsatkich tuzatildi.", "Барча ўзгартирувчи амаллар. Янги турлар: насия, қарз қайтди, харажат, бакка кирим, кўрсаткич тузатилди.", "Все изменяющие действия. Новые типы: долг, возврат долга, расход, приход в бак, исправление показания."),
        ["Audit_Yozuvlar"] = ("Yozuvlar", "Ёзувлар", "Записи"),
        ["Audit_QidiruvPlaceholder"] = ("Foydalanuvchi, amal yoki tafsilot", "Фойдаланувчи, амал ёки тафсилот", "Пользователь, действие или детали"),
        ["Audit_AmalTuri"] = ("Amal turi", "Амал тури", "Тип действия"),
        ["Audit_TurNasiya"] = ("Nasiya", "Насия", "Долги"),
        ["Audit_TurXarajat"] = ("Xarajat", "Харажат", "Расходы"),
        ["Audit_TurBak"] = ("Bak", "Бак", "Бак"),
        ["Audit_TurTuzatish"] = ("Tuzatish", "Тузатиш", "Исправления"),
        ["AsosiyMenyu"] = ("Asosiy menyu", "Асосий меню", "Главное меню"),
        ["ServerAloqaBor"] = ("Server bilan aloqa bor", "Сервер билан алоқа бор", "Связь с сервером есть"),
        ["YorugRejim"] = ("Yorug' rejim", "Ёруғ режим", "Светлый режим"),
        ["MuddatiOtganQarzlarSoni"] = ("{0} ta muddati o'tgan qarz", "{0} та муддати ўтган қарз", "Просроченных долгов: {0}"),
        ["Savdo"] = ("Savdo", "Савдо", "Продажи"),
        ["Nasiyalar"] = ("Nasiyalar", "Насиялар", "Долги"),
        ["Tab_Audit"] = ("Audit", "Аудит", "Аудит"),
        ["Aparat_Raqami"] = ("{0}-aparat", "{0}-аппарат", "Аппарат {0}"),
        ["Smena_Operator"] = ("Smena #{0} · {1}", "Смена #{0} · {1}", "Смена №{0} · {1}"),
        ["Tolov_Naqd"] = ("Naqd", "Нақд", "Наличные"),
        ["Tolov_Plastik"] = ("Plastik", "Пластик", "Пластик"),
        ["Tolov_Depozit"] = ("Depozit", "Депозит", "Депозит"),
        ["Nasiya_Yozish"] = ("Nasiya yozish", "Насия ёзиш", "Записать долг"),
        ["Nasiya_MijozIsmi"] = ("Mijoz ismi", "Мижоз исми", "Имя клиента"),
        ["Nasiya_IsmPlaceholder"] = ("Ism va familiya", "Исм ва фамилия", "Имя и фамилия"),
        ["Nasiya_Telefon"] = ("Telefon", "Телефон", "Телефон"),
        ["Nasiya_MashinaRaqami"] = ("Mashina raqami", "Машина рақами", "Номер машины"),
        ["Nasiya_QarzSummasi"] = ("Qarz summasi, so'm", "Қарз суммаси, сўм", "Сумма долга, сум"),
        ["Nasiya_Muddat"] = ("Qaytarish muddati", "Қайтариш муддати", "Срок возврата"),
        ["Nasiya_Muddat3Kun"] = ("3 kun", "3 кун", "3 дня"),
        ["Nasiya_Muddat1Hafta"] = ("1 hafta", "1 ҳафта", "1 неделя"),
        ["Nasiya_Muddat2Hafta"] = ("2 hafta", "2 ҳафта", "2 недели"),
        ["Nasiya_Muddat1Oy"] = ("1 oy", "1 ой", "1 месяц"),
        ["Nasiya_Sana"] = ("Sana", "Сана", "Дата"),
        ["Nasiya_MuddatIzoh"] = ("{0} gacha · {1} kun", "{0} гача · {1} кун", "до {0} · {1} дн."),
        ["Nasiya_BoshqaSana"] = ("Boshqa sana", "Бошқа сана", "Другая дата"),
        ["Nasiya_Izoh"] = ("Izoh", "Изоҳ", "Комментарий"),
        ["Nasiya_IzohPlaceholder"] = ("Masalan: hafta oxirida to'laydi", "Масалан: ҳафта охирида тўлайди", "Например: заплатит в конце недели"),
        ["Nasiya_YozishIzoh"] = ("Nasiya smena jadvalida \"Nasiya\" qatoriga qo'shiladi va kassada bo'lishi kerak bo'lgan naqddan ayiriladi.", "Насия смена жадвалида \"Насия\" қаторига қўшилади ва кассада бўлиши керак бўлган нақддан айирилади.", "Долг попадёт в строку «Долги» смены и вычтется из наличных, которые должны быть в кассе."),
        ["Nasiya_XatoIsm"] = ("Mijoz ismini yozing", "Мижоз исмини ёзинг", "Укажите имя клиента"),
        ["Nasiya_XatoSumma"] = ("Summani yozing", "Суммани ёзинг", "Укажите сумму"),
        ["Nasiya_XatoMuddat"] = ("Muddatni tanlang", "Муддатни танланг", "Выберите срок"),
        ["Nasiya_QarzQaytdi"] = ("Qarz qaytdi", "Қарз қайтди", "Возврат долга"),
        ["Nasiya_QarzdorniToping"] = ("Qarzdorni toping", "Қарздорни топинг", "Найдите должника"),
        ["Nasiya_Qidiruv"] = ("Ism, telefon yoki mashina raqami", "Исм, телефон ёки машина рақами", "Имя, телефон или номер машины"),
        ["Nasiya_Qarz"] = ("Qarz", "Қарз", "Долг"),
        ["Nasiya_Qaytgan"] = ("Qaytgan", "Қайтган", "Возвращено"),
        ["Nasiya_Qoldiq"] = ("Qoldiq", "Қолдиқ", "Остаток"),
        ["Nasiya_MuddatYorliq"] = ("Muddat", "Муддат", "Срок"),
        ["Nasiya_YozilganSatr"] = ("Yozilgan {0} · smena #{1} · {2}", "Ёзилган {0} · смена #{1} · {2}", "Записан {0} · смена №{1} · {2}"),
        ["Nasiya_QaytarilganSumma"] = ("Qaytarilgan summa, so'm", "Қайтарилган сумма, сўм", "Возвращённая сумма, сум"),
        ["Nasiya_Toliq"] = ("To'liq: {0}", "Тўлиқ: {0}", "Полностью: {0}"),
        ["Nasiya_QandayTolandi"] = ("Qanday to'landi", "Қандай тўланди", "Как оплачено"),
        ["Nasiya_QoladiganQarz"] = ("Qoladigan qarz", "Қоладиган қарз", "Останется долга"),
        ["Nasiya_SummaniYozing"] = ("Summani yozing", "Суммани ёзинг", "Укажите сумму"),
        ["Nasiya_QarzdanKop"] = ("Qarzdan ko'p bo'lishi mumkin emas", "Қарздан кўп бўлиши мумкин эмас", "Не может быть больше долга"),
        ["Nasiya_ToliqYopiladi"] = ("Qarz to'liq yopiladi", "Қарз тўлиқ ёпилади", "Долг будет закрыт полностью"),
        ["Nasiya_MuddatiOtganQoladi"] = ("Muddati {0} edi, o'tgan qarz bo'lib qoladi", "Муддати {0} эди, ўтган қарз бўлиб қолади", "Срок был {0}, останется просроченным"),
        ["Nasiya_MuddatigaQoladi"] = ("Muddat {0} gacha", "Муддат {0} гача", "Срок до {0}"),
        ["Nasiya_QaytishIzoh"] = ("Qaytgan summa smena hisobiga kirim bo'ladi. Naqd bo'lsa kassaga, plastik bo'lsa terminalga, depozit bo'lsa kartaga tushadi.", "Қайтган сумма смена ҳисобига кирим бўлади. Нақд бўлса кассага, пластик бўлса терминалга, депозит бўлса картага тушади.", "Возвращённая сумма пойдёт в приход смены. Наличные — в кассу, пластик — на терминал, депозит — на карту."),
        ["Nasiya_SmenaHisobiga"] = ("Smena hisobiga yozish", "Смена ҳисобига ёзиш", "Записать в счёт смены"),
        ["Nasiya_QarzdorYoq"] = ("Qarzdor topilmadi", "Қарздор топилмади", "Должник не найден"),
        ["Nasiya_KunOtdi"] = ("{0} kun o'tdi", "{0} кун ўтди", "просрочено {0} дн."),
        ["Nasiya_KunQoldi"] = ("{0} kun qoldi", "{0} кун қолди", "осталось {0} дн."),
        ["Nasiya_Ertaga"] = ("Ertaga", "Эртага", "Завтра"),
        ["Nasiya_Bugun"] = ("Bugun", "Бугун", "Сегодня"),
        ["Xarajat_Yozish"] = ("Xarajat yozish", "Харажат ёзиш", "Записать расход"),
        ["Xarajat_Izoh"] = ("Smena #{0} · boshliq aytgan to'lov", "Смена #{0} · бошлиқ айтган тўлов", "Смена №{0} · платёж по указанию начальника"),
        ["Xarajat_Summa"] = ("Summa, so'm", "Сумма, сўм", "Сумма, сум"),
        ["Xarajat_NimaUchun"] = ("Nima uchun", "Нима учун", "Для чего"),
        ["Xarajat_NimaPlaceholder"] = ("Masalan: lampochka sotib olindi", "Масалан: лампочка сотиб олинди", "Например: куплена лампочка"),
        ["Xarajat_Tez1"] = ("Boshliq naqd oldi", "Бошлиқ нақд олди", "Начальник взял наличные"),
        ["Xarajat_Tez2"] = ("Xo'jalik mollari", "Хўжалик моллари", "Хозтовары"),
        ["Xarajat_Tez3"] = ("Ta'mirlash", "Таъмирлаш", "Ремонт"),
        ["Xarajat_PulQayerdan"] = ("Pul qayerdan berildi", "Пул қаердан берилди", "Откуда выданы деньги"),
        ["Xarajat_Kassadan"] = ("Kassadan, naqd", "Кассадан, нақд", "Из кассы, наличные"),
        ["Xarajat_DepozitKartadan"] = ("Depozit kartadan", "Депозит картадан", "С депозитной карты"),
        ["Xarajat_KassaIzoh"] = ("Kassadan berilgan xarajat kassada bo'lishi kerak bo'lgan naqddan ayiriladi.", "Кассадан берилган харажат кассада бўлиши керак бўлган нақддан айирилади.", "Расход из кассы вычитается из наличных, которые должны быть в кассе."),
        ["Xarajat_DepozitIzoh"] = ("Depozit kartadan berilgan xarajat depozit farqi bilan teng chiqadi, kassadagi naqdga ta'sir qilmaydi.", "Депозит картадан берилган харажат депозит фарқи билан тенг чиқади, кассадаги нақдга таъсир қилмайди.", "Расход с депозитной карты уравновешивается разницей депозита и не влияет на наличные в кассе."),
        ["Xarajat_XatoSabab"] = ("Nima uchun ekanini yozing", "Нима учун эканини ёзинг", "Укажите, на что расход"),
        ["Bak_Kirim"] = ("Bakka kirim", "Бакка кирим", "Приход в бак"),
        ["Bak_KirimIzoh"] = ("Zavoddan kelgan yoqilg'i, litrda", "Заводдан келган ёқилғи, литрда", "Топливо с завода, в литрах"),
        ["Bak_QaysiAparat"] = ("Qaysi aparat baki", "Қайси аппарат баки", "Бак какого аппарата"),
        ["Bak_HozirgiQoldiq"] = ("Hozirgi qoldiq", "Ҳозирги қолдиқ", "Текущий остаток"),
        ["Bak_OxirgiKirim"] = ("Oxirgi kirim {0} · +{1} L", "Охирги кирим {0} · +{1} Л", "Последний приход {0} · +{1} л"),
        ["Bak_KirimYoq"] = ("Kirim yo'q", "Кирим йўқ", "Прихода не было"),
        ["Bak_KirimdanKeyin"] = ("Kirimdan keyin", "Киримдан кейин", "После прихода"),
        ["Bak_PultOzgarmaydi"] = ("Pult ko'rsatkichi o'zgarmaydi", "Пулт кўрсаткичи ўзгармайди", "Показание пульта не меняется"),
        ["Bak_KelganMiqdor"] = ("Kelgan miqdor, litr", "Келган миқдор, литр", "Поступило, литров"),
        ["Bak_Hujjat"] = ("Hujjat raqami yoki izoh", "Ҳужжат рақами ёки изоҳ", "Номер документа или комментарий"),
        ["Bak_HujjatPlaceholder"] = ("Yuk xati raqami", "Юк хати рақами", "Номер накладной"),
        ["Bak_KelganVaqt"] = ("Kelgan vaqt", "Келган вақт", "Время прихода"),
        ["Bak_Tushuntirish"] = ("Bak qoldig'i kirimda ko'payadi, har smena yopilganda sotilgan litrga kamayadi. Kirim auditga yoziladi.", "Бак қолдиғи киримда кўпаяди, ҳар смена ёпилганда сотилган литрга камаяди. Кирим аудитга ёзилади.", "Остаток бака растёт при приходе и уменьшается на проданные литры при закрытии смены. Приход записывается в аудит."),
        ["Bak_KirimniSaqlash"] = ("Kirimni saqlash", "Киримни сақлаш", "Сохранить приход"),
        ["Bak_Xato"] = ("Kelgan miqdorni yozing", "Келган миқдорни ёзинг", "Укажите поступившее количество"),
        ["Nasiya_XatoAloqa"] = ("Telefon yoki mashina raqamidan kamida bittasini yozing", "Телефон ёки машина рақамидан камида биттасини ёзинг", "Укажите телефон или номер машины (хотя бы одно)"),
        ["Nasiya_XatoMuddatOtgan"] = ("Muddat bugundan oldin bo'lmasin", "Муддат бугундан олдин бўлмасин", "Срок не может быть раньше сегодняшнего дня"),
        // ==== Smena hisobi — OXIRI
    };
}
