/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginSoroviDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginJavobiDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operatorlar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bak-kirimlar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    aparatId?: number;
                    dan?: string;
                    gacha?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BakKirimDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hisobot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    dan?: string;
                    gacha?: string;
                    operatorId?: number;
                    guruh?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HisobotDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boshqaruv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BoshqaruvDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    tur?: string;
                    dan?: string;
                    gacha?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditYozuviDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/eksport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuditEksportDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zaxira": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZaxiraJavobiDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foydalanuvchilar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FoydalanuvchiYaratishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foydalanuvchilar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FoydalanuvchiTahrirlashDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foydalanuvchilar/{id}/ruxsatlar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RuxsatlarOrnatishDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foydalanuvchilar/{id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PinOrnatishDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yoqilgilar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["YoqilgiTuriDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["YoqilgiYaratishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["YoqilgiTuriDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yoqilgilar/narx-tarixi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NarxTarixiDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yoqilgilar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["YoqilgiTahrirlashDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["YoqilgiTuriDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aparatlar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AparatDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AparatYaratishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AparatDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aparatlar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AparatTahrirlashDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AparatDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aparatlar/{id}/kirim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BakKirimYaratishDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AparatDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    dan?: string;
                    gacha?: string;
                    operatorId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar/joriy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaTafsilotDto"];
                    };
                };
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar/oxirgi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaTafsilotDto"];
                    };
                };
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaTafsilotDto"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar/och": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SmenaOchishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar/{id}/yop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SmenaYopishDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar/{id}/korsatkich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["KorsatkichTuzatishDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaTafsilotDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nasiyalar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    holat?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NasiyalarDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NasiyaYaratishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NasiyaDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nasiyalar/mijozlar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MijozTaklifDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nasiyalar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NasiyaTafsilotDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nasiyalar/{id}/qaytish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NasiyaQaytishiYaratishDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NasiyaDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nasiyalar/qaytishlar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/xarajatlar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    smenaId?: number;
                    dan?: string;
                    gacha?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["XarajatDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["XarajatYaratishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["XarajatDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/xarajatlar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operatorlar/{id}/hisob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    oy?: string;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OperatorHisobDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operatorlar/{id}/harakat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HarakatYaratishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HisobHarakatiDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AparatDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            raqam: number;
            /** Format: int32 */
            yoqilgiTuriId: number;
            yoqilgiNomi: string;
            /** Format: double */
            totalLitr: number;
            /** Format: double */
            bakQoldiq: number;
            /** Format: date-time */
            oxirgiKirimVaqti: null | string;
            /** Format: double */
            oxirgiKirimLitr: null | number;
        };
        AparatKorsatkichDto: {
            /** Format: int32 */
            aparatId: number;
            /** Format: double */
            qiymat: number;
        };
        AparatTahrirlashDto: {
            /** Format: int32 */
            raqam: number;
            /** Format: int32 */
            yoqilgiTuriId: number;
            /** Format: double */
            totalLitr?: null | number;
            /** Format: double */
            bakQoldiq?: null | number;
            sabab?: null | string;
        };
        AparatYaratishDto: {
            /** Format: int32 */
            raqam: number;
            /** Format: int32 */
            yoqilgiTuriId: number;
            /** Format: double */
            boshlangichTotalLitr: number;
            /** Format: double */
            boshlangichBakQoldiq: number;
        };
        AuditEksportDto: {
            turi: string;
            tafsilot: string;
        };
        AuditYozuviDto: {
            /** Format: int32 */
            id: number;
            /** Format: date-time */
            vaqt: string;
            kim: string;
            amal: string;
            tafsilot: string;
            tur: string;
        };
        BakKirimDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            aparatId: number;
            /** Format: int32 */
            aparatRaqam: number;
            /** Format: double */
            litr: number;
            /** Format: double */
            qoldiqOldin: number;
            /** Format: double */
            qoldiqKeyin: number;
            /** Format: date-time */
            vaqt: string;
            hujjat: null | string;
            kimYozdi: string;
        };
        BakKirimYaratishDto: {
            /** Format: double */
            litr: number;
            /** Format: date-time */
            vaqt: null | string;
            hujjat: null | string;
        };
        BoshqaruvDto: {
            joriySmena: null | components["schemas"]["SmenaDto"];
            oxirgiYopilgan: null | components["schemas"]["SmenaDto"];
            /** Format: int64 */
            oySavdo: number;
            /** Format: double */
            oyLitr: number;
            /** Format: int32 */
            oySmenaSoni: number;
            /** Format: int64 */
            oyKamomat: number;
            /** Format: int64 */
            oyOrtiqcha: number;
            nasiyalar: components["schemas"]["NasiyalarXulosaDto"];
            aparatlar: components["schemas"]["AparatDto"][];
            oxirgiSmenalar: components["schemas"]["SmenaQisqaDto"][];
            oyTolovlar: components["schemas"]["TolovTaqsimotiDto"];
            oxirgiYopilganlar: components["schemas"]["SmenaDto"][];
        };
        FoydalanuvchiDto: {
            /** Format: int32 */
            id: number;
            toliqIsm: string;
            login: string;
            rol: components["schemas"]["Rol"];
            faol: boolean;
            /** Format: int64 */
            oylikMaosh: number;
            ruxsatlar: components["schemas"]["Ruxsat"][];
        };
        FoydalanuvchiTahrirlashDto: {
            toliqIsm: string;
            rol: components["schemas"]["Rol"];
            faol: boolean;
            /** Format: int64 */
            oylikMaosh: number;
            login?: null | string;
        };
        FoydalanuvchiYaratishDto: {
            toliqIsm: string;
            login: string;
            rol: components["schemas"]["Rol"];
            /** Format: int64 */
            oylikMaosh: number;
            parolYokiPin: string;
        };
        /** @enum {unknown} */
        HarakatTuri: "Maosh" | "Avans" | "Kamomat" | "Ortiqcha" | "Tolov";
        HarakatYaratishDto: {
            turi: components["schemas"]["HarakatTuri"];
            /** Format: int64 */
            summa: number;
            izoh: string;
        };
        HisobHarakatiDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            operatorId: number;
            /** Format: date-time */
            sana: string;
            turi: components["schemas"]["HarakatTuri"];
            /** Format: int64 */
            summa: number;
            izoh: string;
            kimYozdi: string;
        };
        HisobotAparatDto: {
            /** Format: int32 */
            aparatId: number;
            /** Format: int32 */
            raqam: number;
            yoqilgiNomi: string;
            /** Format: double */
            bakBoshida: number;
            /** Format: double */
            kirim: number;
            /** Format: double */
            sotildi: number;
            /** Format: double */
            bakOxirida: number;
            /** Format: int64 */
            savdo: number;
        };
        HisobotDto: {
            qatorlar: components["schemas"]["HisobotQatoriDto"][];
            jami: components["schemas"]["HisobotQatoriDto"];
            aparatlar: components["schemas"]["HisobotAparatDto"][];
            /** Format: int64 */
            avans: number;
        };
        HisobotQatoriDto: {
            guruh: string;
            /** Format: date */
            sana: null | string;
            operatorIsmi: null | string;
            /** Format: int32 */
            smenaSoni: number;
            /** Format: double */
            litr: number;
            /** Format: int64 */
            savdo: number;
            /** Format: int64 */
            plastik: number;
            /** Format: int64 */
            depozit: number;
            /** Format: int64 */
            nasiya: number;
            /** Format: int64 */
            qaytganNasiya: number;
            /** Format: int64 */
            xarajat: number;
            /** Format: int64 */
            naqdSavdo: number;
            /** Format: int64 */
            kamomat: number;
            /** Format: int64 */
            ortiqcha: number;
            jami: boolean;
            /** Format: int32 */
            xarajatSoni: number;
        };
        KorsatkichTuzatishDto: {
            /** Format: int32 */
            aparatId: number;
            /** Format: double */
            qiymat: number;
            sabab: string;
        };
        LoginJavobiDto: {
            token: string;
            /** Format: date-time */
            tokenMuddati: string;
            foydalanuvchi: components["schemas"]["FoydalanuvchiDto"];
        };
        LoginSoroviDto: {
            login: string;
            parolYokiPin: string;
        };
        MijozTaklifDto: {
            mijozIsmi: string;
            telefon: string;
            mashinaRaqami: string;
            /** Format: int32 */
            nasiyaSoni: number;
            /** Format: int64 */
            faolQarz: number;
            /** Format: date */
            oxirgiNasiya: string;
        };
        NarxTarixiDto: {
            /** Format: date-time */
            vaqt: string;
            yoqilgi: string;
            /** Format: int64 */
            eskiNarx: number;
            /** Format: int64 */
            yangiNarx: number;
            kim: string;
        };
        NasiyaDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            smenaId: number;
            operatorIsmi: string;
            mijozIsmi: string;
            telefon: string;
            mashinaRaqami: string;
            /** Format: int64 */
            summa: number;
            /** Format: int64 */
            qaytgan: number;
            /** Format: int64 */
            qoldiq: number;
            /** Format: date */
            muddat: string;
            holati: components["schemas"]["NasiyaHolati"];
            /** Format: int32 */
            muddatgachaKun: number;
            /** Format: date-time */
            yozildi: string;
            /** Format: date-time */
            yopildi: null | string;
            izoh: null | string;
            /** Format: int32 */
            muallifId: number;
        };
        /** @enum {unknown} */
        NasiyaHolati: "Faol" | "MuddatiOtgan" | "Yopilgan";
        NasiyalarDto: {
            xulosa: components["schemas"]["NasiyalarXulosaDto"];
            royxat: components["schemas"]["NasiyaDto"][];
        };
        NasiyalarXulosaDto: {
            /** Format: int64 */
            faolQarz: number;
            /** Format: int32 */
            faolSoni: number;
            /** Format: int64 */
            muddatiOtgan: number;
            /** Format: int32 */
            muddatiOtganSoni: number;
            /** Format: int64 */
            oyBerilgan: number;
            /** Format: int32 */
            oyBerilganSoni: number;
            /** Format: int64 */
            oyQaytgan: number;
            /** Format: int32 */
            oyQaytganSoni: number;
        };
        NasiyaQaytishiDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            nasiyaId: number;
            mijozIsmi: string;
            /** Format: int32 */
            smenaId: null | number;
            /** Format: int64 */
            summa: number;
            usul: components["schemas"]["TolovTuri"];
            /** Format: date-time */
            vaqt: string;
            kimYozdi: string;
            izoh: null | string;
            /** Format: int32 */
            muallifId: number;
        };
        NasiyaQaytishiYaratishDto: {
            /** Format: int64 */
            summa: number;
            usul: components["schemas"]["TolovTuri"];
            smenaHisobiga: boolean;
            izoh: null | string;
        };
        NasiyaTafsilotDto: {
            nasiya: components["schemas"]["NasiyaDto"];
            qaytishlar: components["schemas"]["NasiyaQaytishiDto"][];
        };
        NasiyaYaratishDto: {
            mijozIsmi: string;
            telefon: string;
            mashinaRaqami: string;
            /** Format: int64 */
            summa: number;
            /** Format: date */
            muddat: string;
            izoh: null | string;
        };
        OperatorHisobDto: {
            /** Format: int32 */
            operatorId: number;
            operatorIsmi: string;
            /** Format: int64 */
            oylikMaosh: number;
            /** Format: int64 */
            oyJami: number;
            /** Format: int64 */
            qoldiq: number;
            /** Format: int64 */
            oySavdo: number;
            /** Format: int32 */
            oySmenalar: number;
            harakatlar: components["schemas"]["HisobHarakatiDto"][];
        };
        PinOrnatishDto: {
            yangiParolYokiPin: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        /** @enum {unknown} */
        Rol: "Operator" | "Boshliq" | "Admin";
        /** @enum {unknown} */
        Ruxsat: "Boshqaruv" | "Savdo" | "SmenaOchish" | "SmenaYopish" | "Smenalar" | "Nasiyalar" | "NasiyaYozish" | "QarzQaytdi" | "XarajatYozish" | "BakKirim" | "KorsatkichTuzatish" | "Hisobotlar" | "Eksport" | "Operatorlar" | "AvansBerish" | "Audit" | "Sozlamalar";
        RuxsatlarOrnatishDto: {
            ruxsatlar: components["schemas"]["Ruxsat"][];
        };
        SmenaDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            operatorId: number;
            operatorIsmi: string;
            /** Format: date-time */
            boshlandi: string;
            /** Format: date-time */
            tugadi: null | string;
            /** Format: int64 */
            ochishQaytim: number;
            /** Format: int64 */
            ochishTerminal: number;
            /** Format: int64 */
            ochishDepozit: number;
            /** Format: int64 */
            yopishTerminal: null | number;
            /** Format: int64 */
            yopishDepozit: null | number;
            /** Format: int64 */
            sanalganNaqd: null | number;
            /** Format: double */
            jamiLitr: number;
            /** Format: int64 */
            savdo: number;
            /** Format: int64 */
            plastik: number;
            /** Format: int64 */
            depozitFarqi: number;
            /** Format: int64 */
            nasiyaJami: number;
            /** Format: int64 */
            qaytganNasiya: number;
            /** Format: int64 */
            xarajatJami: number;
            /** Format: int64 */
            kutilgan: number;
            /** Format: int64 */
            farq: number;
            izoh: null | string;
        };
        SmenaKorsatkichDto: {
            /** Format: int32 */
            aparatId: number;
            /** Format: int32 */
            aparatRaqam: number;
            yoqilgiNomi: string;
            /** Format: double */
            boshi: number;
            /** Format: double */
            oxiri: number;
            /** Format: int64 */
            narx: number;
            /** Format: double */
            litr: number;
            /** Format: int64 */
            summa: number;
            narxOzgarishida: boolean;
        };
        SmenaOchishDto: {
            /** Format: int64 */
            qaytim: number;
            /** Format: int64 */
            terminal: number;
            /** Format: int64 */
            depozit: number;
        };
        SmenaQisqaDto: {
            /** Format: int32 */
            id: number;
            /** Format: date */
            sana: string;
            operatorIsmi: string;
            /** Format: int64 */
            savdo: number;
            /** Format: double */
            litr: number;
            /** Format: int64 */
            farq: number;
        };
        SmenaTafsilotDto: {
            smena: components["schemas"]["SmenaDto"];
            korsatkichlar: components["schemas"]["SmenaKorsatkichDto"][];
            nasiyalar: components["schemas"]["NasiyaDto"][];
            qaytishlar: components["schemas"]["NasiyaQaytishiDto"][];
            xarajatlar: components["schemas"]["XarajatDto"][];
        };
        SmenaYopishDto: {
            korsatkichlar: components["schemas"]["AparatKorsatkichDto"][];
            /** Format: int64 */
            terminal: number;
            /** Format: int64 */
            depozit: number;
            /** Format: int64 */
            sanalganNaqd: number;
            izoh: null | string;
        };
        TolovTaqsimotiDto: {
            /** Format: int64 */
            naqd: number;
            /** Format: int64 */
            plastik: number;
            /** Format: int64 */
            depozit: number;
            /** Format: int64 */
            nasiya: number;
        };
        /** @enum {unknown} */
        TolovTuri: "Naqd" | "Plastik" | "Depozit";
        XarajatDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            smenaId: number;
            /** Format: int64 */
            summa: number;
            sabab: string;
            manba: components["schemas"]["XarajatManbai"];
            /** Format: date-time */
            vaqt: string;
            kimYozdi: string;
            /** Format: int32 */
            muallifId: number;
        };
        /** @enum {unknown} */
        XarajatManbai: "Kassa" | "Depozit";
        XarajatYaratishDto: {
            /** Format: int64 */
            summa: number;
            sabab: string;
            manba: components["schemas"]["XarajatManbai"];
        };
        YoqilgiTahrirlashDto: {
            nomi: string;
            /** Format: int64 */
            narx: number;
            rang: string;
            korsatkichlar?: null | components["schemas"]["AparatKorsatkichDto"][];
        };
        YoqilgiTuriDto: {
            /** Format: int32 */
            id: number;
            nomi: string;
            /** Format: int64 */
            narx: number;
            rang: string;
            aparatgaBiriktirilgan: boolean;
        };
        YoqilgiYaratishDto: {
            nomi: string;
            /** Format: int64 */
            narx: number;
            rang: string;
        };
        ZaxiraJavobiDto: {
            faylNomi: string;
            /** Format: int64 */
            hajmBayt: number;
            /** Format: date-time */
            vaqt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
