// <auto-generated />
using System;
using FuelControl.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelControl.Api.Data.Migrations
{
    [DbContext(typeof(FuelControlDbContext))]
    partial class FuelControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FuelControl.Core.Modellar.Aparat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BakQoldiq")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Raqam")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalLitr")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("YoqilgiTuriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Raqam")
                        .IsUnique();

                    b.HasIndex("YoqilgiTuriId");

                    b.ToTable("Aparatlar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.AuditYozuvi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tafsilot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Tur");

                    b.HasIndex("Vaqt");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.BakKirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AparatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hujjat")
                        .HasColumnType("TEXT");

                    b.Property<string>("KimYozdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Litr")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QoldiqKeyin")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QoldiqOldin")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AparatId", "Vaqt");

                    b.ToTable("BakKirimlari");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.BakTuzatishi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AparatId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Keyin")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("KimYozdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Oldin")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sabab")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AparatId", "Vaqt");

                    b.ToTable("BakTuzatishlari");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Foydalanuvchi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BlokGacha")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Faol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OylikMaosh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParolXeshi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruxsatlar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToliqIsm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("XatoUrinishlar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Foydalanuvchilar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.HisobHarakati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izoh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KimYozdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaoshOyi")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.Property<long>("Summa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "MaoshOyi")
                        .IsUnique()
                        .HasDatabaseName("IX_Harakatlar_MaoshOyi")
                        .HasFilter("\"MaoshOyi\" IS NOT NULL");

                    b.HasIndex("OperatorId", "Sana");

                    b.ToTable("Harakatlar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.NarxTarixi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EskiNarx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vaqt")
                        .HasColumnType("TEXT");

                    b.Property<long>("YangiNarx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YoqilgiNomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YoqilgiTuriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Vaqt");

                    b.ToTable("NarxTarixlari");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Nasiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izoh")
                        .HasColumnType("TEXT");

                    b.Property<string>("KimYozdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MashinaRaqami")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MijozIsmi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Muddat")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Qaytgan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmenaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Summa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Yopildi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Yozildi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("SmenaId");

                    b.HasIndex("Yozildi");

                    b.ToTable("Nasiyalar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.NasiyaQaytishi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izoh")
                        .HasColumnType("TEXT");

                    b.Property<string>("KimYozdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NasiyaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SmenaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Summa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NasiyaId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("SmenaId");

                    b.HasIndex("Vaqt");

                    b.ToTable("NasiyaQaytishlari");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Smena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Boshlandi")
                        .HasColumnType("TEXT");

                    b.Property<long>("DepozitFarqi")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Farq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izoh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("JamiLitr")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("Kutilgan")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NasiyaJami")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OchishDepozit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OchishQaytim")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OchishTerminal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Plastik")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QaytganNasiya")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SanalganNaqd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Savdo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Tugadi")
                        .HasColumnType("TEXT");

                    b.Property<long>("XarajatJami")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("YopishDepozit")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("YopishTerminal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Boshlandi");

                    b.HasIndex("OperatorId", "Tugadi");

                    b.ToTable("Smenalar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.SmenaKorsatkichi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AparatId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Boshi")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Litr")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("Narx")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NarxOzgarishida")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Oxiri")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SmenaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Summa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tartib")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Vaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AparatId");

                    b.HasIndex("SmenaId", "AparatId", "Tartib")
                        .IsUnique();

                    b.ToTable("SmenaKorsatkichlari");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Xarajat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KimYozdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manba")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sabab")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SmenaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Summa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Vaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("SmenaId");

                    b.ToTable("Xarajatlar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.YoqilgiTuri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Narx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nomi")
                        .IsUnique();

                    b.ToTable("Yoqilgilar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Aparat", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.YoqilgiTuri", null)
                        .WithMany()
                        .HasForeignKey("YoqilgiTuriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.BakKirim", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Aparat", null)
                        .WithMany()
                        .HasForeignKey("AparatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.BakTuzatishi", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Aparat", null)
                        .WithMany()
                        .HasForeignKey("AparatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.HisobHarakati", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Foydalanuvchi", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Nasiya", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Foydalanuvchi", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuelControl.Core.Modellar.Smena", null)
                        .WithMany()
                        .HasForeignKey("SmenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.NasiyaQaytishi", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Nasiya", null)
                        .WithMany()
                        .HasForeignKey("NasiyaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuelControl.Core.Modellar.Foydalanuvchi", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuelControl.Core.Modellar.Smena", null)
                        .WithMany()
                        .HasForeignKey("SmenaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Smena", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Foydalanuvchi", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.SmenaKorsatkichi", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Aparat", null)
                        .WithMany()
                        .HasForeignKey("AparatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuelControl.Core.Modellar.Smena", null)
                        .WithMany()
                        .HasForeignKey("SmenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Xarajat", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Foydalanuvchi", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuelControl.Core.Modellar.Smena", null)
                        .WithMany()
                        .HasForeignKey("SmenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
